from typing import List, Dict, Any

TOOLS: List[Dict[str, Any]] = [
    # ─── CATEGORY 1: Network Scanning ───────────────────────────────────────
    {
        "id": "nmap",
        "name": "Nmap",
        "description": "Network port scanner with service detection, OS fingerprinting, and vuln scripts.",
        "category": "Network Scanning",
        "difficulty": "Beginner",
        "estimatedTime": "10-120s",
        "command": "nmap",
        "tags": ["scanning", "ports", "enumeration"],
        "learnContent": "Nmap (Network Mapper) is the industry standard port scanner. It discovers open ports, running services, OS versions, and can run vulnerability scripts. Essential for every network assessment.\n\n**Common flags:**\n- `-sV` — Probe open ports to determine service/version info\n- `-O` — Enable OS detection\n- `-A` — Aggressive: OS detection, version, script scan, traceroute\n- `-p-` — Scan all 65535 ports\n- `--script vuln` — Run vulnerability detection scripts\n- `-sU` — UDP scan\n- `-T4` — Faster timing template\n\n**Example:** `nmap -sV -O -p 1-1000 192.168.0.1`\n\n**What to look for:** Open ports you didn't expect, outdated service versions, default service banners.",
        "params": [
            {"name": "target", "label": "Target IP/Range", "type": "text", "defaultValue": "192.168.0.0/24", "placeholder": "192.168.0.1 or 192.168.0.0/24", "required": True},
            {"name": "scan_type", "label": "Scan Type", "type": "select", "defaultValue": "-sV", "placeholder": None, "required": True},
            {"name": "ports", "label": "Port Range", "type": "text", "defaultValue": "1-1000", "placeholder": "1-65535 or 80,443,8080", "required": False},
            {"name": "extra_flags", "label": "Extra Flags", "type": "text", "defaultValue": "", "placeholder": "-T4 --open", "required": False},
        ],
        "commandTemplate": "nmap {scan_type} -p {ports} {extra_flags} {target}",
    },
    {
        "id": "masscan",
        "name": "Masscan",
        "description": "Fastest port scanner. Scans full networks in seconds with configurable rate limiting.",
        "category": "Network Scanning",
        "difficulty": "Intermediate",
        "estimatedTime": "5-30s",
        "command": "masscan",
        "tags": ["scanning", "fast", "network"],
        "learnContent": "Masscan can scan the entire internet in under 6 minutes. For a /24 subnet it's nearly instant. Uses its own TCP/IP stack for maximum speed.\n\n**Key flags:**\n- `--rate` — packets per second (be careful, high rates can saturate your network)\n- `-p` — port range\n- `--banners` — grab service banners\n\n**Example:** `masscan 192.168.0.0/24 -p 0-65535 --rate 10000`",
        "params": [
            {"name": "target", "label": "Target Range", "type": "text", "defaultValue": "192.168.0.0/24", "placeholder": "192.168.0.0/24", "required": True},
            {"name": "ports", "label": "Port Range", "type": "text", "defaultValue": "0-65535", "placeholder": "0-65535", "required": True},
            {"name": "rate", "label": "Rate (pps)", "type": "text", "defaultValue": "10000", "placeholder": "10000", "required": False},
        ],
        "commandTemplate": "masscan {target} -p {ports} --rate {rate}",
    },
    {
        "id": "netdiscover",
        "name": "Netdiscover",
        "description": "Find all live devices on 192.168.0.x via ARP. Shows IP, MAC, and vendor.",
        "category": "Network Scanning",
        "difficulty": "Beginner",
        "estimatedTime": "15-60s",
        "command": "netdiscover",
        "tags": ["arp", "discovery", "network"],
        "learnContent": "Netdiscover uses ARP (Address Resolution Protocol) to discover live hosts on a local network. Since ARP operates at Layer 2, it can find hosts that block ICMP ping.\n\n**Example:** `netdiscover -r 192.168.0.0/24`",
        "params": [
            {"name": "range", "label": "IP Range", "type": "text", "defaultValue": "192.168.0.0/24", "placeholder": "192.168.0.0/24", "required": True},
            {"name": "interface", "label": "Interface", "type": "text", "defaultValue": "eth0", "placeholder": "eth0 or wlan0", "required": False},
        ],
        "commandTemplate": "netdiscover -r {range} -i {interface}",
    },
    {
        "id": "arp-scan",
        "name": "ARP-scan",
        "description": "ARP-based device discovery with vendor lookup from MAC address.",
        "category": "Network Scanning",
        "difficulty": "Beginner",
        "estimatedTime": "5-15s",
        "command": "arp-scan",
        "tags": ["arp", "discovery", "vendor"],
        "learnContent": "arp-scan sends ARP packets and displays responses with MAC address and vendor information. Very fast and reliable for local network discovery.",
        "params": [
            {"name": "target", "label": "Target", "type": "text", "defaultValue": "192.168.0.0/24", "placeholder": "192.168.0.0/24 or --localnet", "required": True},
            {"name": "interface", "label": "Interface", "type": "text", "defaultValue": "eth0", "placeholder": "eth0", "required": False},
        ],
        "commandTemplate": "arp-scan --interface={interface} {target}",
    },
    {
        "id": "fping",
        "name": "Fping",
        "description": "Fast ping sweep of multiple hosts simultaneously. Much faster than sequential ping.",
        "category": "Network Scanning",
        "difficulty": "Beginner",
        "estimatedTime": "5-20s",
        "command": "fping",
        "tags": ["ping", "sweep", "discovery"],
        "learnContent": "fping pings multiple hosts in parallel, making subnet sweeps very fast. Use -g for range generation, -a to show only alive hosts.",
        "params": [
            {"name": "target", "label": "Target Range", "type": "text", "defaultValue": "192.168.0.0/24", "placeholder": "192.168.0.0/24", "required": True},
        ],
        "commandTemplate": "fping -a -g {target}",
    },
    {
        "id": "sslscan",
        "name": "SSLscan",
        "description": "SSL/TLS configuration scanner. Finds weak ciphers, expired certs, protocol versions.",
        "category": "Network Scanning",
        "difficulty": "Intermediate",
        "estimatedTime": "10-30s",
        "command": "sslscan",
        "tags": ["ssl", "tls", "certificates"],
        "learnContent": "SSLscan tests SSL/TLS services and reports: supported cipher suites, protocol versions (SSLv2, SSLv3, TLS 1.0-1.3), certificate details, and vulnerabilities like HEARTBLEED and POODLE.",
        "params": [
            {"name": "target", "label": "Target (host:port)", "type": "text", "defaultValue": "192.168.0.1:443", "placeholder": "host:443", "required": True},
        ],
        "commandTemplate": "sslscan {target}",
    },
    {
        "id": "enum4linux",
        "name": "Enum4linux",
        "description": "Linux/Samba enumeration tool. Extracts users, groups, shares from Windows/Linux SMB.",
        "category": "Network Scanning",
        "difficulty": "Intermediate",
        "estimatedTime": "20-60s",
        "command": "enum4linux",
        "tags": ["smb", "samba", "enumeration", "windows"],
        "learnContent": "Enum4linux enumerates information from Windows and Samba systems: user accounts, group memberships, shared folders, OS information, password policies.",
        "params": [
            {"name": "target", "label": "Target IP", "type": "text", "defaultValue": "192.168.0.1", "placeholder": "192.168.0.x", "required": True},
            {"name": "flags", "label": "Flags", "type": "text", "defaultValue": "-a", "placeholder": "-a (all)", "required": False},
        ],
        "commandTemplate": "enum4linux {flags} {target}",
    },
    {
        "id": "fierce",
        "name": "Fierce",
        "description": "DNS reconnaissance tool. Zone transfers, subdomain brute force, network range discovery.",
        "category": "Network Scanning",
        "difficulty": "Intermediate",
        "estimatedTime": "30-120s",
        "command": "fierce",
        "tags": ["dns", "recon", "subdomains"],
        "learnContent": "Fierce performs DNS reconnaissance: attempts zone transfers, brutes subdomains with a wordlist, finds nearby IP ranges, and maps the network perimeter.",
        "params": [
            {"name": "domain", "label": "Domain", "type": "text", "defaultValue": "", "placeholder": "example.com", "required": True},
        ],
        "commandTemplate": "fierce --domain {domain}",
    },

    # ─── CATEGORY 2: WiFi Security ───────────────────────────────────────────
    {
        "id": "airmon-ng",
        "name": "Airmon-ng",
        "description": "Put wireless interface into monitor mode and kill interfering processes.",
        "category": "WiFi Security",
        "difficulty": "Intermediate",
        "estimatedTime": "5s",
        "command": "airmon-ng",
        "tags": ["wifi", "monitor-mode", "wireless"],
        "learnContent": "Airmon-ng enables monitor mode on wireless interfaces, which allows capturing all WiFi traffic rather than just traffic addressed to your device. Always run `airmon-ng check kill` first to stop processes that interfere.",
        "params": [
            {"name": "action", "label": "Action", "type": "select", "defaultValue": "start", "placeholder": None, "required": True},
            {"name": "interface", "label": "Interface", "type": "text", "defaultValue": "wlan0", "placeholder": "wlan0", "required": True},
        ],
        "commandTemplate": "airmon-ng {action} {interface}",
    },
    {
        "id": "airodump-ng",
        "name": "Airodump-ng",
        "description": "Scan nearby WiFi networks, capture WPA2 handshakes, track clients per AP.",
        "category": "WiFi Security",
        "difficulty": "Intermediate",
        "estimatedTime": "30-300s",
        "command": "airodump-ng",
        "tags": ["wifi", "capture", "handshake", "scanning"],
        "learnContent": "Airodump-ng captures raw 802.11 frames. Use it to discover APs, their BSSIDs, channels, encryption types, and associated clients. Can capture WPA2 4-way handshakes for offline cracking.",
        "params": [
            {"name": "interface", "label": "Interface (monitor mode)", "type": "text", "defaultValue": "wlan0mon", "placeholder": "wlan0mon", "required": True},
            {"name": "bssid", "label": "BSSID (optional)", "type": "text", "defaultValue": "", "placeholder": "AA:BB:CC:DD:EE:FF", "required": False},
            {"name": "channel", "label": "Channel (optional)", "type": "text", "defaultValue": "", "placeholder": "6", "required": False},
            {"name": "write", "label": "Output File Prefix", "type": "text", "defaultValue": "/tmp/capture", "placeholder": "/tmp/capture", "required": False},
        ],
        "commandTemplate": "airodump-ng {interface} --bssid {bssid} -c {channel} -w {write}",
    },
    {
        "id": "aircrack-ng",
        "name": "Aircrack-ng",
        "description": "Crack WPA2 handshakes using wordlists. Works on captures from airodump-ng.",
        "category": "WiFi Security",
        "difficulty": "Advanced",
        "estimatedTime": "1-60min",
        "command": "aircrack-ng",
        "tags": ["wifi", "cracking", "wpa2", "wordlist"],
        "learnContent": "Aircrack-ng performs dictionary attacks against captured WPA2 4-way handshakes. The capture file must contain a complete handshake. Speed depends on CPU and wordlist size.\n\n**Example:** `aircrack-ng -w /usr/share/wordlists/rockyou.txt capture-01.cap`",
        "params": [
            {"name": "wordlist", "label": "Wordlist Path", "type": "text", "defaultValue": "/usr/share/wordlists/rockyou.txt", "placeholder": "/usr/share/wordlists/rockyou.txt", "required": True},
            {"name": "capture", "label": "Capture File (.cap)", "type": "text", "defaultValue": "/tmp/capture-01.cap", "placeholder": "/tmp/capture-01.cap", "required": True},
        ],
        "commandTemplate": "aircrack-ng -w {wordlist} {capture}",
    },
    {
        "id": "wifite2",
        "name": "Wifite2",
        "description": "Automated WiFi auditing. Runs the full attack chain automatically against your own network.",
        "category": "WiFi Security",
        "difficulty": "Intermediate",
        "estimatedTime": "2-30min",
        "command": "wifite",
        "tags": ["wifi", "automated", "wpa2", "wps"],
        "learnContent": "Wifite2 automates WiFi attacks: puts interface in monitor mode, scans for targets, then attempts WPS attacks, PMKID attacks, and handshake capture+crack automatically.",
        "params": [
            {"name": "interface", "label": "Interface", "type": "text", "defaultValue": "wlan0", "placeholder": "wlan0", "required": True},
        ],
        "commandTemplate": "wifite --interface {interface} --kill",
    },

    {
        "id": "aireplay-ng",
        "name": "Aireplay-ng",
        "description": "Send 802.11 deauth frames to force a client off an AP and capture a WPA2 handshake on reconnect.",
        "category": "WiFi Security",
        "difficulty": "Intermediate",
        "estimatedTime": "5-30s",
        "command": "aireplay-ng",
        "tags": ["wifi", "deauth", "injection", "wpa2"],
        "learnContent": "Aireplay-ng injects raw 802.11 frames. The most common use is sending deauthentication frames (`-0`) to disconnect a client from an AP, which forces it to re-authenticate — capturing the WPA2 4-way handshake.\n\n**Deauth attack:** `aireplay-ng -0 5 -a <BSSID> -c <CLIENT_MAC> wlan0mon`\n\nAlways use on your own network. Requires monitor mode and packet injection capability.",
        "params": [
            {"name": "count", "label": "Deauth Packets", "type": "text", "defaultValue": "5", "placeholder": "5", "required": True},
            {"name": "bssid", "label": "AP BSSID", "type": "text", "defaultValue": "AA:BB:CC:DD:EE:FF", "placeholder": "AA:BB:CC:DD:EE:FF", "required": True},
            {"name": "client", "label": "Client MAC (optional)", "type": "text", "defaultValue": "", "placeholder": "11:22:33:44:55:66", "required": False},
            {"name": "interface", "label": "Monitor Interface", "type": "text", "defaultValue": "wlan0mon", "placeholder": "wlan0mon", "required": True},
        ],
        "commandTemplate": "aireplay-ng -0 {count} -a {bssid} -c {client} {interface}",
    },
    {
        "id": "wash",
        "name": "Wash",
        "description": "Scan for WPS-enabled access points and report their WPS version, lock status, and RSSI.",
        "category": "WiFi Security",
        "difficulty": "Beginner",
        "estimatedTime": "15-60s",
        "command": "wash",
        "tags": ["wifi", "wps", "scanning", "discovery"],
        "learnContent": "Wash scans for access points broadcasting WPS (Wi-Fi Protected Setup) information elements. It reports BSSID, channel, RSSI, WPS version, and whether WPS is locked (indicating failed PIN attempts). WPS-enabled APs may be vulnerable to Reaver or Pixie Dust attacks.\n\n**Example:** `wash -i wlan0mon`",
        "params": [
            {"name": "interface", "label": "Monitor Interface", "type": "text", "defaultValue": "wlan0mon", "placeholder": "wlan0mon", "required": True},
        ],
        "commandTemplate": "wash -i {interface}",
    },
    {
        "id": "reaver",
        "name": "Reaver",
        "description": "Brute-force WPS PINs to recover the WPA2 passphrase. Targets WPS-enabled APs.",
        "category": "WiFi Security",
        "difficulty": "Advanced",
        "estimatedTime": "1-24hr",
        "command": "reaver",
        "tags": ["wifi", "wps", "brute-force", "pin"],
        "learnContent": "Reaver performs an online brute-force attack against WPS PINs. WPS PINs are 8 digits but due to the checksum and split-validation design, only 11,000 combinations need to be tried. On vulnerable APs this can recover the WPA2 passphrase in hours.\n\n**Example:** `reaver -i wlan0mon -b <BSSID> -vv`\n\nMany modern routers lock WPS after failed attempts. Use `wash` first to check WPS lock status.",
        "params": [
            {"name": "interface", "label": "Monitor Interface", "type": "text", "defaultValue": "wlan0mon", "placeholder": "wlan0mon", "required": True},
            {"name": "bssid", "label": "Target BSSID", "type": "text", "defaultValue": "AA:BB:CC:DD:EE:FF", "placeholder": "AA:BB:CC:DD:EE:FF", "required": True},
        ],
        "commandTemplate": "reaver -i {interface} -b {bssid} -vv",
    },
    {
        "id": "pixiewps",
        "name": "Pixiewps",
        "description": "Pixie Dust offline WPS PIN attack. Recovers PIN in seconds from a single authentication exchange.",
        "category": "WiFi Security",
        "difficulty": "Advanced",
        "estimatedTime": "5-60s",
        "command": "pixiewps",
        "tags": ["wifi", "wps", "pixie-dust", "offline"],
        "learnContent": "Pixie Dust is an offline WPS attack that exploits weak random number generation in some router chipsets (Ralink, Realtek, Broadcom). Unlike Reaver's online brute-force, Pixie Dust recovers the WPS PIN from a single M1/M2 exchange in seconds.\n\n**Use via Reaver:** `reaver -i wlan0mon -b <BSSID> -K 1 -vv`\n\nAffected chipsets: many older Ralink RT3xx/RT5xx, some Realtek and Broadcom.",
        "params": [
            {"name": "pke", "label": "PKe (from WPS exchange)", "type": "text", "defaultValue": "", "placeholder": "hex string from M1", "required": True},
            {"name": "pkr", "label": "PKr (from WPS exchange)", "type": "text", "defaultValue": "", "placeholder": "hex string from M2", "required": True},
            {"name": "e_hash1", "label": "E-Hash1", "type": "text", "defaultValue": "", "placeholder": "hex", "required": True},
            {"name": "e_hash2", "label": "E-Hash2", "type": "text", "defaultValue": "", "placeholder": "hex", "required": True},
        ],
        "commandTemplate": "pixiewps -e {pke} -r {pkr} -s {e_hash1} -z {e_hash2}",
    },
    {
        "id": "hcxdumptool",
        "name": "Hcxdumptool",
        "description": "Capture PMKID frames and EAPOL handshakes for offline WPA2/WPA3 cracking with hashcat.",
        "category": "WiFi Security",
        "difficulty": "Advanced",
        "estimatedTime": "30s-5min",
        "command": "hcxdumptool",
        "tags": ["wifi", "pmkid", "wpa3", "capture", "hashcat"],
        "learnContent": "Hcxdumptool captures PMKID frames (RSN IE from AP beacon/probe responses) and full EAPOL handshakes. PMKIDs can be captured without any associated client — just AP presence is sufficient. Captured .pcapng files are converted with `hcxpcapngtool` for hashcat (mode 22000).\n\n**Workflow:**\n1. `hcxdumptool -o capture.pcapng -i wlan0mon`\n2. `hcxpcapngtool capture.pcapng -o hashes.hc22000`\n3. `hashcat -m 22000 hashes.hc22000 rockyou.txt`",
        "params": [
            {"name": "interface", "label": "Monitor Interface", "type": "text", "defaultValue": "wlan0mon", "placeholder": "wlan0mon", "required": True},
            {"name": "output", "label": "Output File (.pcapng)", "type": "text", "defaultValue": "/tmp/pmkid.pcapng", "placeholder": "/tmp/pmkid.pcapng", "required": True},
            {"name": "duration", "label": "Duration (seconds, 0=indefinite)", "type": "text", "defaultValue": "60", "placeholder": "60", "required": False},
        ],
        "commandTemplate": "hcxdumptool -o {output} -i {interface} --active_beacon --enable_status=1",
    },
    {
        "id": "hcxpcapngtool",
        "name": "Hcxpcapngtool",
        "description": "Convert pcapng captures from hcxdumptool to hashcat format 22000 for offline WPA2/WPA3 cracking.",
        "category": "WiFi Security",
        "difficulty": "Intermediate",
        "estimatedTime": "2-10s",
        "command": "hcxpcapngtool",
        "tags": ["wifi", "hashcat", "wpa2", "conversion", "pmkid"],
        "learnContent": "Hcxpcapngtool extracts authentication material (PMKID, EAPOL) from pcapng files and outputs them in hashcat format 22000 (replaces the older 2500/2501 formats). A single file can contain both PMKID and EAPOL hashes.\n\n**Example:** `hcxpcapngtool capture.pcapng -o hashes.hc22000 --csv=nets.csv`\n\nThen crack with: `hashcat -m 22000 hashes.hc22000 /usr/share/wordlists/rockyou.txt`",
        "params": [
            {"name": "input", "label": "Input .pcapng File", "type": "text", "defaultValue": "/tmp/pmkid.pcapng", "placeholder": "/tmp/capture.pcapng", "required": True},
            {"name": "output", "label": "Output Hash File", "type": "text", "defaultValue": "/tmp/hashes.hc22000", "placeholder": "/tmp/hashes.hc22000", "required": True},
        ],
        "commandTemplate": "hcxpcapngtool {input} -o {output}",
    },
    {
        "id": "kismet",
        "name": "Kismet",
        "description": "Passive 802.11 WiFi, Bluetooth, and Zigbee scanner. No injection — purely passive capture and logging.",
        "category": "WiFi Security",
        "difficulty": "Intermediate",
        "estimatedTime": "continuous",
        "command": "kismet",
        "tags": ["wifi", "passive", "scanning", "bluetooth", "wardriving"],
        "learnContent": "Kismet is a passive wireless network detector that captures 802.11 traffic, Bluetooth, Zigbee, and more. It does not inject frames, making it more stealthy than active scanners. Data is logged to SQLite databases and accessible via a web interface on port 2501.\n\n**Start server:** `kismet -c wlan0mon`\n**Web UI:** http://localhost:2501",
        "params": [
            {"name": "interface", "label": "Capture Interface", "type": "text", "defaultValue": "wlan0mon", "placeholder": "wlan0mon", "required": True},
        ],
        "commandTemplate": "kismet -c {interface} --no-ncurses",
    },
    {
        "id": "mdk4",
        "name": "MDK4",
        "description": "802.11 protocol attack tool: beacon flood, deauth flood, authentication DoS, SSID brute-force.",
        "category": "WiFi Security",
        "difficulty": "Advanced",
        "estimatedTime": "10s-continuous",
        "command": "mdk4",
        "tags": ["wifi", "deauth", "beacon-flood", "dos", "attack"],
        "learnContent": "MDK4 tests the robustness of wireless infrastructure against management frame attacks.\n\n**Modes:**\n- `b` — Beacon flood (fake SSIDs)\n- `d` — Deauthentication/disassociation flood\n- `a` — Authentication DoS (flood AP auth table)\n- `p` — SSID probing and brute-force\n- `e` — EAPOL logoff\n\n**Example (deauth flood):** `mdk4 wlan0mon d -B AA:BB:CC:DD:EE:FF`",
        "params": [
            {"name": "interface", "label": "Monitor Interface", "type": "text", "defaultValue": "wlan0mon", "placeholder": "wlan0mon", "required": True},
            {"name": "mode", "label": "Attack Mode (b/d/a/p/e)", "type": "text", "defaultValue": "d", "placeholder": "d", "required": True},
            {"name": "bssid", "label": "Target BSSID (optional)", "type": "text", "defaultValue": "", "placeholder": "AA:BB:CC:DD:EE:FF", "required": False},
        ],
        "commandTemplate": "mdk4 {interface} {mode} -B {bssid}",
    },
    {
        "id": "iw",
        "name": "Iw",
        "description": "Configure wireless interfaces, scan for APs, set monitor mode, list PHY capabilities.",
        "category": "WiFi Security",
        "difficulty": "Beginner",
        "estimatedTime": "2-15s",
        "command": "iw",
        "tags": ["wifi", "interface", "scanning", "management"],
        "learnContent": "iw is the modern Linux wireless configuration tool (replacing the deprecated iwconfig). Use it to set interface modes, scan for access points, list regulatory domains, and inspect PHY capabilities.\n\n**Useful commands:**\n- `iw dev` — list wireless interfaces\n- `iw dev wlan0 scan` — active scan for APs\n- `iw phy` — list PHY capabilities (supported bands, modes)\n- `iw dev wlan0 set type monitor` — set monitor mode",
        "params": [
            {"name": "interface", "label": "Interface", "type": "text", "defaultValue": "wlan0", "placeholder": "wlan0", "required": True},
        ],
        "commandTemplate": "iw dev {interface} scan",
    },

    # ─── CATEGORY 3: Web Application Testing ────────────────────────────────
    {
        "id": "nikto",
        "name": "Nikto",
        "description": "Full web server vulnerability scanner. Checks for 6700+ dangerous files and outdated software.",
        "category": "Web Application Testing",
        "difficulty": "Beginner",
        "estimatedTime": "1-10min",
        "command": "nikto",
        "tags": ["web", "scanning", "vulnerabilities"],
        "learnContent": "Nikto scans web servers for dangerous files, outdated server software, version-specific problems, and server configuration issues. It performs over 6700 checks.",
        "params": [
            {"name": "target", "label": "Target URL", "type": "text", "defaultValue": "http://192.168.0.1", "placeholder": "http://192.168.0.x", "required": True},
            {"name": "port", "label": "Port", "type": "text", "defaultValue": "80", "placeholder": "80", "required": False},
        ],
        "commandTemplate": "nikto -h {target} -p {port}",
    },
    {
        "id": "gobuster",
        "name": "Gobuster",
        "description": "Directory, file, DNS, and VHost brute force scanner. Fast Go-based tool.",
        "category": "Web Application Testing",
        "difficulty": "Beginner",
        "estimatedTime": "30s-5min",
        "command": "gobuster",
        "tags": ["web", "directory", "bruteforce", "discovery"],
        "learnContent": "Gobuster brute forces URIs, DNS subdomains, and virtual host names. Much faster than Dirb due to Go concurrency.\n\n**Modes:** dir (directories), dns (subdomains), vhost (virtual hosts)\n\n**Example:** `gobuster dir -u http://target -w /usr/share/wordlists/dirb/common.txt`",
        "params": [
            {"name": "url", "label": "Target URL", "type": "text", "defaultValue": "http://192.168.0.1", "placeholder": "http://192.168.0.x", "required": True},
            {"name": "wordlist", "label": "Wordlist", "type": "text", "defaultValue": "/usr/share/wordlists/dirb/common.txt", "placeholder": "/usr/share/wordlists/...", "required": True},
            {"name": "threads", "label": "Threads", "type": "text", "defaultValue": "50", "placeholder": "50", "required": False},
        ],
        "commandTemplate": "gobuster dir -u {url} -w {wordlist} -t {threads}",
    },
    {
        "id": "sqlmap",
        "name": "SQLmap",
        "description": "Automated SQL injection detection and exploitation. Supports all major databases.",
        "category": "Web Application Testing",
        "difficulty": "Advanced",
        "estimatedTime": "1-30min",
        "command": "sqlmap",
        "tags": ["web", "sql-injection", "database"],
        "learnContent": "SQLmap automates the detection and exploitation of SQL injection vulnerabilities. It can dump databases, read files, execute commands. Use only on your own systems.\n\n**Example:** `sqlmap -u 'http://target/page?id=1' --dbs`",
        "params": [
            {"name": "url", "label": "Target URL", "type": "text", "defaultValue": "http://192.168.0.1/page?id=1", "placeholder": "http://target/page?id=1", "required": True},
            {"name": "level", "label": "Level (1-5)", "type": "text", "defaultValue": "1", "placeholder": "1", "required": False},
            {"name": "extra", "label": "Extra Flags", "type": "text", "defaultValue": "--dbs", "placeholder": "--dbs --tables --dump", "required": False},
        ],
        "commandTemplate": "sqlmap -u '{url}' --level={level} --batch {extra}",
    },
    {
        "id": "nuclei",
        "name": "Nuclei",
        "description": "Fast template-based vulnerability scanner with 5000+ community templates.",
        "category": "Web Application Testing",
        "difficulty": "Intermediate",
        "estimatedTime": "1-10min",
        "command": "nuclei",
        "tags": ["web", "vulnerabilities", "templates", "scanning"],
        "learnContent": "Nuclei uses YAML-based templates to detect vulnerabilities, misconfigurations, CVEs, and exposures. Templates cover web apps, APIs, DNS, network protocols, and more.",
        "params": [
            {"name": "target", "label": "Target URL", "type": "text", "defaultValue": "http://192.168.0.1", "placeholder": "http://192.168.0.x", "required": True},
            {"name": "severity", "label": "Severity Filter", "type": "select", "defaultValue": "medium,high,critical", "placeholder": None, "required": False},
        ],
        "commandTemplate": "nuclei -u {target} -severity {severity}",
    },
    {
        "id": "ffuf",
        "name": "ffuf",
        "description": "Fast web fuzzer for content discovery, parameter fuzzing, and subdomain enumeration.",
        "category": "Web Application Testing",
        "difficulty": "Intermediate",
        "estimatedTime": "30s-5min",
        "command": "ffuf",
        "tags": ["web", "fuzzing", "discovery"],
        "learnContent": "ffuf (Fuzz Faster U Fool) is an extremely fast web fuzzer. Use FUZZ keyword in URL, headers, POST data. Supports filtering by status code, size, words, lines.",
        "params": [
            {"name": "url", "label": "Target URL (use FUZZ)", "type": "text", "defaultValue": "http://192.168.0.1/FUZZ", "placeholder": "http://target/FUZZ", "required": True},
            {"name": "wordlist", "label": "Wordlist", "type": "text", "defaultValue": "/usr/share/wordlists/dirb/common.txt", "placeholder": "/usr/share/wordlists/...", "required": True},
        ],
        "commandTemplate": "ffuf -w {wordlist} -u {url}",
    },
    {
        "id": "wpscan",
        "name": "WPScan",
        "description": "WordPress CMS vulnerability scanner. Finds plugins, themes, users, and CVEs.",
        "category": "Web Application Testing",
        "difficulty": "Beginner",
        "estimatedTime": "1-5min",
        "command": "wpscan",
        "tags": ["web", "wordpress", "cms", "scanning"],
        "learnContent": "WPScan is purpose-built for WordPress. It enumerates: installed plugins and themes with known vulnerabilities, user accounts, XML-RPC status, exposed wp-config files.",
        "params": [
            {"name": "url", "label": "WordPress URL", "type": "text", "defaultValue": "http://192.168.0.1", "placeholder": "http://target", "required": True},
            {"name": "enumerate", "label": "Enumerate", "type": "text", "defaultValue": "ap,u,t", "placeholder": "ap,u,t (plugins,users,themes)", "required": False},
        ],
        "commandTemplate": "wpscan --url {url} --enumerate {enumerate} --no-banner",
    },

    # ─── CATEGORY 4: Password & Hash Testing ────────────────────────────────
    {
        "id": "hashcat",
        "name": "Hashcat",
        "description": "GPU-accelerated hash cracker. Supports 300+ hash types: MD5, SHA, bcrypt, NTLM, WPA2.",
        "category": "Password & Hash Testing",
        "difficulty": "Advanced",
        "estimatedTime": "1min-hours",
        "command": "hashcat",
        "tags": ["cracking", "hash", "gpu", "wordlist"],
        "learnContent": "Hashcat is the world's fastest password cracker. It leverages GPU computation.\n\n**Attack modes (-a):**\n- 0: Dictionary attack\n- 1: Combinator attack\n- 3: Brute-force/mask attack\n- 6: Hybrid wordlist+mask\n\n**Common hash types (-m):**\n- 0: MD5, 100: SHA1, 1400: SHA256, 1700: SHA512\n- 1000: NTLM, 3200: bcrypt, 22000: WPA2\n\n**Example:** `hashcat -m 0 -a 0 hashes.txt rockyou.txt`",
        "params": [
            {"name": "hashfile", "label": "Hash File", "type": "text", "defaultValue": "/tmp/hashes.txt", "placeholder": "/tmp/hashes.txt", "required": True},
            {"name": "wordlist", "label": "Wordlist", "type": "text", "defaultValue": "/usr/share/wordlists/rockyou.txt", "placeholder": "/usr/share/wordlists/rockyou.txt", "required": True},
            {"name": "hashtype", "label": "Hash Type (-m)", "type": "text", "defaultValue": "0", "placeholder": "0 (MD5), 1000 (NTLM), 22000 (WPA2)", "required": True},
            {"name": "attack", "label": "Attack Mode (-a)", "type": "text", "defaultValue": "0", "placeholder": "0 (dict), 3 (brute)", "required": False},
        ],
        "commandTemplate": "hashcat -m {hashtype} -a {attack} {hashfile} {wordlist}",
    },
    {
        "id": "john",
        "name": "John the Ripper",
        "description": "CPU hash cracker with auto hash-type detection. Wordlist + rules modes.",
        "category": "Password & Hash Testing",
        "difficulty": "Intermediate",
        "estimatedTime": "1min-hours",
        "command": "john",
        "tags": ["cracking", "hash", "cpu", "wordlist"],
        "learnContent": "John the Ripper automatically detects hash types and applies smart mangling rules to wordlists. The community-enhanced 'jumbo' version supports 400+ hash types.",
        "params": [
            {"name": "hashfile", "label": "Hash File", "type": "text", "defaultValue": "/tmp/hashes.txt", "placeholder": "/tmp/hashes.txt", "required": True},
            {"name": "wordlist", "label": "Wordlist", "type": "text", "defaultValue": "/usr/share/wordlists/rockyou.txt", "placeholder": "/usr/share/wordlists/rockyou.txt", "required": False},
        ],
        "commandTemplate": "john {hashfile} --wordlist={wordlist}",
    },
    {
        "id": "hydra",
        "name": "Hydra",
        "description": "Network login brute forcer. Supports SSH, FTP, HTTP, Telnet, SMB, RDP, and more.",
        "category": "Password & Hash Testing",
        "difficulty": "Intermediate",
        "estimatedTime": "1-30min",
        "command": "hydra",
        "tags": ["brute-force", "login", "network", "credentials"],
        "learnContent": "Hydra performs fast parallel login attacks against network services. Supports 50+ protocols.\n\n**Example:** `hydra -l admin -P rockyou.txt ssh://192.168.0.1`\n\n**Protocols:** ssh, ftp, http-get, http-post-form, smb, rdp, mysql, telnet",
        "params": [
            {"name": "target", "label": "Target IP", "type": "text", "defaultValue": "192.168.0.1", "placeholder": "192.168.0.x", "required": True},
            {"name": "protocol", "label": "Protocol", "type": "select", "defaultValue": "ssh", "placeholder": None, "required": True},
            {"name": "username", "label": "Username / User List", "type": "text", "defaultValue": "admin", "placeholder": "admin or /tmp/users.txt", "required": True},
            {"name": "passlist", "label": "Password List", "type": "text", "defaultValue": "/usr/share/wordlists/rockyou.txt", "placeholder": "/usr/share/wordlists/rockyou.txt", "required": True},
            {"name": "threads", "label": "Threads", "type": "text", "defaultValue": "16", "placeholder": "16", "required": False},
        ],
        "commandTemplate": "hydra -l {username} -P {passlist} -t {threads} {protocol}://{target}",
    },

    # ─── CATEGORY 5: Exploitation Framework ─────────────────────────────────
    {
        "id": "searchsploit",
        "name": "SearchSploit",
        "description": "Search offline ExploitDB for known exploits. Shows full exploit code.",
        "category": "Exploitation Framework",
        "difficulty": "Beginner",
        "estimatedTime": "2-5s",
        "command": "searchsploit",
        "tags": ["exploits", "cve", "database", "search"],
        "learnContent": "SearchSploit is an offline command-line interface to ExploitDB. Search by software name, version, CVE. Use `-x` to examine exploit code, `-m` to copy to current directory.",
        "params": [
            {"name": "query", "label": "Search Query", "type": "text", "defaultValue": "", "placeholder": "apache 2.4 or vsftpd 2.3.4", "required": True},
        ],
        "commandTemplate": "searchsploit {query}",
    },
    {
        "id": "msfvenom",
        "name": "MSFvenom",
        "description": "Generate Metasploit payloads for all platforms and formats.",
        "category": "Exploitation Framework",
        "difficulty": "Advanced",
        "estimatedTime": "5-15s",
        "command": "msfvenom",
        "tags": ["payload", "metasploit", "shellcode"],
        "learnContent": "MSFvenom combines msfpayload and msfencode into one tool for payload generation.\n\n**Example (Linux reverse shell ELF):**\n`msfvenom -p linux/x64/shell_reverse_tcp LHOST=192.168.0.172 LPORT=4444 -f elf -o shell.elf`",
        "params": [
            {"name": "payload", "label": "Payload", "type": "text", "defaultValue": "linux/x64/shell_reverse_tcp", "placeholder": "linux/x64/shell_reverse_tcp", "required": True},
            {"name": "lhost", "label": "LHOST", "type": "text", "defaultValue": "192.168.0.172", "placeholder": "192.168.0.172", "required": True},
            {"name": "lport", "label": "LPORT", "type": "text", "defaultValue": "4444", "placeholder": "4444", "required": True},
            {"name": "format", "label": "Format (-f)", "type": "text", "defaultValue": "elf", "placeholder": "elf, exe, py, raw", "required": True},
            {"name": "output", "label": "Output File", "type": "text", "defaultValue": "/tmp/shell.elf", "placeholder": "/tmp/payload", "required": True},
        ],
        "commandTemplate": "msfvenom -p {payload} LHOST={lhost} LPORT={lport} -f {format} -o {output}",
    },
    {
        "id": "routersploit",
        "name": "RouterSploit",
        "description": "Embedded device exploitation framework for testing your own router.",
        "category": "Exploitation Framework",
        "difficulty": "Intermediate",
        "estimatedTime": "30-120s",
        "command": "rsf.py",
        "tags": ["router", "iot", "exploitation", "embedded"],
        "learnContent": "RouterSploit is a specialized exploitation framework for routers and embedded devices. It includes scanner modules that check for known vulnerabilities in common router models.",
        "params": [
            {"name": "target", "label": "Target IP", "type": "text", "defaultValue": "192.168.0.1", "placeholder": "192.168.0.1", "required": True},
        ],
        "commandTemplate": "python3 /usr/share/routersploit/rsf.py --target {target}",
    },

    # ─── CATEGORY 6: Honeypot Testing ────────────────────────────────────────
    {
        "id": "cowrie-ssh-trigger",
        "name": "Cowrie SSH Trigger",
        "description": "Simulate SSH brute force against your Cowrie honeypot to verify it captures correctly.",
        "category": "Honeypot Testing",
        "difficulty": "Beginner",
        "estimatedTime": "10-30s",
        "command": "hydra",
        "tags": ["honeypot", "cowrie", "ssh", "testing"],
        "learnContent": "Tests that your Cowrie SSH honeypot is working by attempting controlled login attempts. Verify the attempts appear in Cowrie logs at /var/log/cowrie/cowrie.log.",
        "params": [
            {"name": "target", "label": "Cowrie Target IP", "type": "text", "defaultValue": "192.168.0.125", "placeholder": "192.168.0.125 (Pi Zero)", "required": True},
            {"name": "port", "label": "SSH Port", "type": "text", "defaultValue": "2222", "placeholder": "2222", "required": True},
        ],
        "commandTemplate": "hydra -l root -p password123 -t 4 -s {port} ssh://{target}",
    },
    {
        "id": "honeypot-health-check",
        "name": "Full Honeypot Health Check",
        "description": "Verify all honeypots on your network are alive and capturing. Shows status dashboard.",
        "category": "Honeypot Testing",
        "difficulty": "Beginner",
        "estimatedTime": "10-30s",
        "command": "nmap",
        "tags": ["honeypot", "health", "monitoring"],
        "learnContent": "Pings and port-scans your honeypot infrastructure to verify all services are listening. Checks Cowrie (SSH/Telnet), Dionaea (SMB/FTP/HTTP), Conpot (Modbus/SNMP), Endlessh, etc.",
        "params": [
            {"name": "honeypot_ip", "label": "Honeypot Host IP", "type": "text", "defaultValue": "192.168.0.125", "placeholder": "192.168.0.125", "required": True},
        ],
        "commandTemplate": "nmap -sV -p 22,23,2222,2223,445,21,80,161,502,25 {honeypot_ip}",
    },

    # ─── CATEGORY 7: Packet Analysis ─────────────────────────────────────────
    {
        "id": "tcpdump",
        "name": "tcpdump",
        "description": "Capture packets on any interface. Filter by host, port, protocol. Download PCAP.",
        "category": "Packet Analysis",
        "difficulty": "Intermediate",
        "estimatedTime": "30s-5min",
        "command": "tcpdump",
        "tags": ["capture", "packets", "pcap", "network"],
        "learnContent": "tcpdump is the foundational packet capture tool. Uses BPF (Berkeley Packet Filter) syntax for filtering.\n\n**Common filters:**\n- `host 192.168.0.1` — traffic to/from IP\n- `port 80` — HTTP traffic\n- `tcp` — TCP only\n- `not arp` — exclude ARP\n\n**Example:** `tcpdump -i eth0 -w /tmp/capture.pcap host 192.168.0.1`",
        "params": [
            {"name": "interface", "label": "Interface", "type": "text", "defaultValue": "eth0", "placeholder": "eth0 or any", "required": True},
            {"name": "filter", "label": "BPF Filter", "type": "text", "defaultValue": "", "placeholder": "host 192.168.0.1 or port 80", "required": False},
            {"name": "count", "label": "Packet Count", "type": "text", "defaultValue": "100", "placeholder": "100", "required": False},
            {"name": "output", "label": "Output File", "type": "text", "defaultValue": "/tmp/capture.pcap", "placeholder": "/tmp/capture.pcap", "required": False},
        ],
        "commandTemplate": "tcpdump -i {interface} -c {count} -w {output} {filter}",
    },
    {
        "id": "hping3",
        "name": "hping3",
        "description": "Custom packet crafter and network testing tool. All protocols, TTL, flags, payload.",
        "category": "Packet Analysis",
        "difficulty": "Advanced",
        "estimatedTime": "10-60s",
        "command": "hping3",
        "tags": ["packets", "crafting", "testing", "firewall"],
        "learnContent": "hping3 can craft and send arbitrary TCP/IP packets. Use it to test firewalls, probe services, perform traceroutes, or simulate network traffic.",
        "params": [
            {"name": "target", "label": "Target IP", "type": "text", "defaultValue": "192.168.0.1", "placeholder": "192.168.0.x", "required": True},
            {"name": "flags", "label": "Flags", "type": "text", "defaultValue": "-S -p 80", "placeholder": "-S (SYN), -A (ACK), -F (FIN)", "required": False},
            {"name": "count", "label": "Count", "type": "text", "defaultValue": "5", "placeholder": "5", "required": False},
        ],
        "commandTemplate": "hping3 {flags} -c {count} {target}",
    },
    {
        "id": "netcat",
        "name": "Netcat",
        "description": "Raw TCP/UDP tester. Send custom data, listen mode, port scanning, file transfer.",
        "category": "Packet Analysis",
        "difficulty": "Beginner",
        "estimatedTime": "5-30s",
        "command": "nc",
        "tags": ["tcp", "udp", "raw", "banner-grabbing"],
        "learnContent": "Netcat is the 'Swiss army knife' of networking. Uses: banner grabbing, port scanning, file transfer, reverse shells, relay connections.\n\n**Example (banner grab):** `nc -v 192.168.0.1 80`\n**Example (listen):** `nc -lvnp 4444`",
        "params": [
            {"name": "target", "label": "Target IP", "type": "text", "defaultValue": "192.168.0.1", "placeholder": "192.168.0.x", "required": True},
            {"name": "port", "label": "Port", "type": "text", "defaultValue": "80", "placeholder": "80", "required": True},
            {"name": "flags", "label": "Flags", "type": "text", "defaultValue": "-v", "placeholder": "-v -z (scan mode)", "required": False},
        ],
        "commandTemplate": "nc {flags} {target} {port}",
    },

    # ─── CATEGORY 8: Bluetooth & RF ─────────────────────────────────────────
    {
        "id": "bluetoothctl",
        "name": "Bluetoothctl",
        "description": "Scan nearby Bluetooth devices, pair, show services and device info.",
        "category": "Bluetooth & RF",
        "difficulty": "Beginner",
        "estimatedTime": "10-30s",
        "command": "bluetoothctl",
        "tags": ["bluetooth", "scanning", "devices"],
        "learnContent": "bluetoothctl is the standard Linux Bluetooth control tool. Use it to discover nearby BR/EDR and LE devices, query device information, and manage pairing.",
        "params": [],
        "commandTemplate": "bluetoothctl -- scan on",
    },
    {
        "id": "rtl-sdr",
        "name": "RTL-SDR Scanner",
        "description": "Software-defined radio frequency scanner. Detect signals, AM/FM/WFM decode.",
        "category": "Bluetooth & RF",
        "difficulty": "Intermediate",
        "estimatedTime": "30s-5min",
        "command": "rtl_power",
        "tags": ["sdr", "radio", "rf", "scanner"],
        "learnContent": "RTL-SDR turns a $25 USB dongle into a software-defined radio. rtl_power scans a frequency range and outputs signal strength data.",
        "params": [
            {"name": "freq_low", "label": "Start Frequency (MHz)", "type": "text", "defaultValue": "88", "placeholder": "88", "required": True},
            {"name": "freq_high", "label": "End Frequency (MHz)", "type": "text", "defaultValue": "108", "placeholder": "108", "required": True},
        ],
        "commandTemplate": "rtl_power -f {freq_low}M:{freq_high}M:125k -g 50 -i 1 -e 30 /tmp/scan.csv",
    },

    {
        "id": "hcitool",
        "name": "Hcitool",
        "description": "Classic Bluetooth inquiry scanner. Discovers nearby BR/EDR devices, reads device name, clock, and signal strength.",
        "category": "Bluetooth & RF",
        "difficulty": "Beginner",
        "estimatedTime": "10-30s",
        "command": "hcitool",
        "tags": ["bluetooth", "scanning", "inquiry", "classic"],
        "learnContent": "Hcitool provides low-level Bluetooth HCI control. The `scan` command runs a standard BR/EDR inquiry to find discoverable devices. `inq` shows raw inquiry data including clock offset. `info` queries a specific device for its name, features, and version.\n\n**Commands:**\n- `hcitool scan` — find discoverable devices\n- `hcitool inq` — raw inquiry with RSSI\n- `hcitool info <BDADDR>` — detailed device info\n- `hcitool lescan` — BLE advertisement scan",
        "params": [],
        "commandTemplate": "hcitool scan",
    },
    {
        "id": "hcitool-le",
        "name": "Hcitool LE Scan",
        "description": "Scan for Bluetooth Low Energy (BLE) advertisement packets. Lists all nearby BLE devices and their MAC addresses.",
        "category": "Bluetooth & RF",
        "difficulty": "Beginner",
        "estimatedTime": "15-30s",
        "command": "hcitool",
        "tags": ["ble", "bluetooth", "scanning", "iot", "le"],
        "learnContent": "BLE devices broadcast advertisement packets that can be passively captured. `hcitool lescan` listens for these packets and displays the device MAC address and name.\n\n**Types of BLE advertisements:**\n- `ADV_IND` — connectable undirected (most common)\n- `ADV_NONCONN_IND` — non-connectable (beacons, sensors)\n- `ADV_DIRECT_IND` — targeted connection request\n\n**Note:** Requires root privileges to access the HCI socket.",
        "params": [
            {"name": "interface", "label": "HCI Interface", "type": "text", "defaultValue": "hci0", "placeholder": "hci0", "required": False},
        ],
        "commandTemplate": "hcitool -i {interface} lescan",
    },
    {
        "id": "btscanner",
        "name": "Btscanner",
        "description": "Brute-force Bluetooth device discovery — finds devices even when set to non-discoverable mode.",
        "category": "Bluetooth & RF",
        "difficulty": "Intermediate",
        "estimatedTime": "30s-5min",
        "command": "btscanner",
        "tags": ["bluetooth", "discovery", "brute-force", "stealth"],
        "learnContent": "Btscanner sends inquiry requests to all possible Bluetooth addresses in range, finding devices even when they are configured as non-discoverable. It enriches results with manufacturer OUI lookups and device class decoding.\n\n**Use case:** Discover hidden Bluetooth devices on the GowskiNet network that have disabled discoverability but are still listening for connections.\n\n**Note:** Runs interactively with an ncurses UI. Press `i` to start inquiry, `b` to start brute-force scan.",
        "params": [],
        "commandTemplate": "btscanner",
    },
    {
        "id": "gatttool",
        "name": "Gatttool",
        "description": "Browse and read/write Bluetooth LE GATT attributes — explore services, characteristics, and descriptors.",
        "category": "Bluetooth & RF",
        "difficulty": "Intermediate",
        "estimatedTime": "10-60s",
        "command": "gatttool",
        "tags": ["ble", "gatt", "attributes", "iot", "bluetooth-le"],
        "learnContent": "GATT (Generic Attribute Profile) is the framework for BLE data exchange. Gatttool lets you connect to a BLE peripheral and explore its attribute table.\n\n**Workflow:**\n1. `hcitool lescan` — find target MAC\n2. `gatttool -b <MAC> -I` — connect interactively\n3. `primary` — list services\n4. `characteristics` — list characteristics with handles\n5. `char-read-hnd <handle>` — read a characteristic\n6. `char-write-req <handle> <value>` — write a value\n\n**Example IoT attack:** Read unencrypted sensor data or write to a BLE lock characteristic.",
        "params": [
            {"name": "target", "label": "Target BLE MAC", "type": "text", "defaultValue": "AA:BB:CC:DD:EE:FF", "placeholder": "AA:BB:CC:DD:EE:FF", "required": True},
        ],
        "commandTemplate": "gatttool -b {target} --primary",
    },
    {
        "id": "sdptool",
        "name": "Sdptool",
        "description": "Browse Bluetooth SDP service records. Lists all services advertised by a classic Bluetooth device.",
        "category": "Bluetooth & RF",
        "difficulty": "Beginner",
        "estimatedTime": "5-15s",
        "command": "sdptool",
        "tags": ["bluetooth", "sdp", "services", "enumeration"],
        "learnContent": "The Service Discovery Protocol (SDP) is how Bluetooth devices advertise services. Sdptool queries the SDP database of a remote device to list all services it offers (A2DP audio, SPP serial, HFP headset, OBEX file transfer, etc.).\n\n**Example:** `sdptool browse AA:BB:CC:DD:EE:FF`\n\nThis reveals what a Bluetooth speaker, headset, keyboard, or IoT device can do — useful for understanding attack surface before connecting.",
        "params": [
            {"name": "target", "label": "Target Bluetooth MAC", "type": "text", "defaultValue": "AA:BB:CC:DD:EE:FF", "placeholder": "AA:BB:CC:DD:EE:FF", "required": True},
        ],
        "commandTemplate": "sdptool browse {target}",
    },
    {
        "id": "l2ping",
        "name": "L2ping",
        "description": "Send Bluetooth L2CAP echo requests (Bluetooth ping). Checks reachability and measures RTT to a classic BT device.",
        "category": "Bluetooth & RF",
        "difficulty": "Beginner",
        "estimatedTime": "5-15s",
        "command": "l2ping",
        "tags": ["bluetooth", "ping", "reachability", "l2cap"],
        "learnContent": "L2ping sends L2CAP echo request packets to a Bluetooth device and measures the round-trip time — similar to ICMP ping for IP networks. Useful for:\n- Verifying Bluetooth reachability to a device\n- Testing range and signal quality\n- Historical: L2CAP flooding attacks (patched in modern kernels)\n\n**Example:** `l2ping -c 5 AA:BB:CC:DD:EE:FF`",
        "params": [
            {"name": "target", "label": "Target Bluetooth MAC", "type": "text", "defaultValue": "AA:BB:CC:DD:EE:FF", "placeholder": "AA:BB:CC:DD:EE:FF", "required": True},
            {"name": "count", "label": "Ping Count", "type": "text", "defaultValue": "5", "placeholder": "5", "required": False},
        ],
        "commandTemplate": "l2ping -c {count} {target}",
    },
    {
        "id": "bettercap-ble",
        "name": "Bettercap BLE",
        "description": "BLE reconnaissance: enumerate advertisement packets, GATT services, and characteristics via bettercap's ble.recon module.",
        "category": "Bluetooth & RF",
        "difficulty": "Intermediate",
        "estimatedTime": "30-120s",
        "command": "bettercap",
        "tags": ["ble", "bettercap", "gatt", "iot", "recon"],
        "learnContent": "Bettercap's BLE module provides a unified framework for BLE recon and interaction. It continuously captures advertisement packets, resolves device names, and optionally enumerates GATT services/characteristics for all discovered devices.\n\n**Caplet commands:**\n- `ble.recon on` — start passive BLE scan\n- `ble.show` — display discovered devices\n- `ble.enum <MAC>` — enumerate all GATT attributes\n- `ble.write <MAC> <UUID> <hex>` — write to a characteristic\n\n**Use case:** Enumerate smart home devices on the GowskiNet IoT segment.",
        "params": [],
        "commandTemplate": "bettercap -eval 'ble.recon on; ticker on; ticker.period 5; ticker.commands ble.show'",
    },
    {
        "id": "rtl433",
        "name": "RTL_433",
        "description": "Decode 433/868/915 MHz ISM band transmissions from IoT sensors: weather stations, door sensors, power meters.",
        "category": "Bluetooth & RF",
        "difficulty": "Intermediate",
        "estimatedTime": "30s-continuous",
        "command": "rtl_433",
        "tags": ["sdr", "iot", "433mhz", "sensors", "rf"],
        "learnContent": "rtl_433 (supports more than 433MHz) decodes transmissions from hundreds of IoT devices using an RTL-SDR dongle. Common targets on a home network: Acurite/Oregon Scientific weather stations, TPMS tire sensors, door/window sensors, smart meters, remote controls.\n\n**Usage:**\n- `rtl_433` — auto-detect and decode all known protocols\n- `rtl_433 -f 915M` — scan 915 MHz band\n- `rtl_433 -F json` — output as JSON for logging\n- `rtl_433 -R 0 -X` — probe unknown signals\n\nOutputs decoded sensor data in real-time — can reveal unencrypted IoT data.",
        "params": [
            {"name": "freq", "label": "Frequency (e.g. 433M, 868M, 915M)", "type": "text", "defaultValue": "433M", "placeholder": "433M", "required": False},
        ],
        "commandTemplate": "rtl_433 -f {freq} -F json",
    },
    {
        "id": "hackrf-info",
        "name": "HackRF Info",
        "description": "Detect and display HackRF One hardware information: firmware version, serial number, supported frequency range.",
        "category": "Bluetooth & RF",
        "difficulty": "Beginner",
        "estimatedTime": "2s",
        "command": "hackrf_info",
        "tags": ["hackrf", "sdr", "hardware", "rf"],
        "learnContent": "HackRF One is a wideband SDR peripheral capable of transmitting and receiving from 1 MHz to 6 GHz. `hackrf_info` queries connected hardware for firmware version, serial number, and board revision.\n\n**Capabilities:**\n- Frequency: 1 MHz – 6 GHz\n- Bandwidth: up to 20 MHz\n- Half-duplex TX/RX\n- Can transmit signals — use only on licensed frequencies or in a shielded environment\n\nRequires `hackrf` package and HackRF hardware connected via USB.",
        "params": [],
        "commandTemplate": "hackrf_info",
    },
    {
        "id": "ubertooth-scan",
        "name": "Ubertooth Scan",
        "description": "2.4 GHz Bluetooth sniffing with Ubertooth One: follow piconets, capture BDRs, decode advertising channels.",
        "category": "Bluetooth & RF",
        "difficulty": "Advanced",
        "estimatedTime": "30s-continuous",
        "command": "ubertooth-scan",
        "tags": ["ubertooth", "bluetooth", "2.4ghz", "sniffing", "piconet"],
        "learnContent": "Ubertooth One is an open-source 2.4 GHz wireless development platform designed for Bluetooth experimentation. Unlike regular BT adapters, it can follow frequency-hopping piconets and capture non-discoverable traffic.\n\n**Tools:**\n- `ubertooth-scan` — active Bluetooth scan\n- `ubertooth-btle -f -c capture.pcap` — follow and capture BLE\n- `ubertooth-rx` — raw 2.4GHz packet capture\n- `ubertooth-specan` — spectrum analyzer\n\nRequires Ubertooth One hardware + `ubertooth` package.",
        "params": [],
        "commandTemplate": "ubertooth-scan -t 30",
    },

    # ─── CATEGORY 9: Stress Testing ──────────────────────────────────────────
    {
        "id": "iperf3",
        "name": "Iperf3",
        "description": "Network bandwidth test between your machines. Client and server mode.",
        "category": "Stress Testing",
        "difficulty": "Beginner",
        "estimatedTime": "10-60s",
        "command": "iperf3",
        "tags": ["bandwidth", "network", "performance"],
        "learnContent": "iperf3 measures maximum achievable bandwidth between two hosts. Run a server on one machine (`iperf3 -s`) and client on another.\n\n**Example (client):** `iperf3 -c 192.168.0.x -t 10`",
        "params": [
            {"name": "target", "label": "Server IP", "type": "text", "defaultValue": "192.168.0.1", "placeholder": "192.168.0.x", "required": True},
            {"name": "duration", "label": "Duration (seconds)", "type": "text", "defaultValue": "10", "placeholder": "10", "required": False},
            {"name": "parallel", "label": "Parallel Streams", "type": "text", "defaultValue": "1", "placeholder": "1", "required": False},
        ],
        "commandTemplate": "iperf3 -c {target} -t {duration} -P {parallel}",
    },
    {
        "id": "siege",
        "name": "Siege",
        "description": "HTTP load testing tool. Configurable concurrent users and duration.",
        "category": "Stress Testing",
        "difficulty": "Intermediate",
        "estimatedTime": "30s-5min",
        "command": "siege",
        "tags": ["http", "load-testing", "web", "benchmark"],
        "learnContent": "Siege simulates concurrent users hitting a web server. Reports hits/sec, avg response time, concurrency, and data transferred.",
        "params": [
            {"name": "url", "label": "Target URL", "type": "text", "defaultValue": "http://192.168.0.1", "placeholder": "http://192.168.0.x", "required": True},
            {"name": "concurrency", "label": "Concurrent Users", "type": "text", "defaultValue": "25", "placeholder": "25", "required": False},
            {"name": "duration", "label": "Duration", "type": "text", "defaultValue": "30s", "placeholder": "30s or 1m", "required": False},
        ],
        "commandTemplate": "siege -c {concurrency} -t {duration} {url}",
    },
    {
        "id": "stress-ng",
        "name": "Stress-ng",
        "description": "CPU, RAM, disk, network stress test on your own machine. All subsystems.",
        "category": "Stress Testing",
        "difficulty": "Beginner",
        "estimatedTime": "30s-5min",
        "command": "stress-ng",
        "tags": ["cpu", "ram", "disk", "stress", "benchmark"],
        "learnContent": "stress-ng applies configurable load to CPU, memory, I/O, and network subsystems. Use for thermal testing, stability validation, and performance benchmarking.",
        "params": [
            {"name": "cpu", "label": "CPU Workers", "type": "text", "defaultValue": "4", "placeholder": "4", "required": False},
            {"name": "vm", "label": "VM Workers", "type": "text", "defaultValue": "2", "placeholder": "2", "required": False},
            {"name": "timeout", "label": "Timeout", "type": "text", "defaultValue": "30s", "placeholder": "30s", "required": False},
        ],
        "commandTemplate": "stress-ng --cpu {cpu} --vm {vm} --timeout {timeout} --metrics-brief",
    },

    # ─── CATEGORY 10: Forensics & Analysis ───────────────────────────────────
    {
        "id": "binwalk",
        "name": "Binwalk",
        "description": "Firmware and binary analysis. Extract embedded files, entropy analysis.",
        "category": "Forensics & Analysis",
        "difficulty": "Intermediate",
        "estimatedTime": "5-30s",
        "command": "binwalk",
        "tags": ["forensics", "firmware", "binary", "extraction"],
        "learnContent": "Binwalk analyzes binary files to find embedded firmware, filesystems, archives, and executable code. Use -e to automatically extract detected components.",
        "params": [
            {"name": "file", "label": "Target File", "type": "text", "defaultValue": "/tmp/firmware.bin", "placeholder": "/tmp/firmware.bin", "required": True},
            {"name": "flags", "label": "Flags", "type": "text", "defaultValue": "-e", "placeholder": "-e (extract) -E (entropy)", "required": False},
        ],
        "commandTemplate": "binwalk {flags} {file}",
    },
    {
        "id": "exiftool",
        "name": "ExifTool",
        "description": "Extract all metadata from images, PDFs, Office docs, videos. Timestamps, GPS, camera info.",
        "category": "Forensics & Analysis",
        "difficulty": "Beginner",
        "estimatedTime": "1-5s",
        "command": "exiftool",
        "tags": ["metadata", "forensics", "images", "documents"],
        "learnContent": "ExifTool reads and writes metadata in files. Useful for forensics: extracting GPS coordinates from photos, identifying document authors, finding creation timestamps.",
        "params": [
            {"name": "file", "label": "Target File", "type": "text", "defaultValue": "/tmp/image.jpg", "placeholder": "/tmp/file.jpg", "required": True},
        ],
        "commandTemplate": "exiftool {file}",
    },
    {
        "id": "strings",
        "name": "Strings",
        "description": "Extract all printable strings from any binary file. Find URLs, keys, passwords.",
        "category": "Forensics & Analysis",
        "difficulty": "Beginner",
        "estimatedTime": "1-5s",
        "command": "strings",
        "tags": ["forensics", "binary", "strings", "analysis"],
        "learnContent": "strings extracts printable character sequences from binary files. Very fast way to find hardcoded passwords, URLs, API keys, version strings, and debug messages.",
        "params": [
            {"name": "file", "label": "Target File", "type": "text", "defaultValue": "/tmp/binary", "placeholder": "/tmp/binary or /bin/ls", "required": True},
            {"name": "min_length", "label": "Min String Length", "type": "text", "defaultValue": "8", "placeholder": "8", "required": False},
        ],
        "commandTemplate": "strings -n {min_length} {file}",
    },
    {
        "id": "lynis",
        "name": "Lynis",
        "description": "Full local system security audit. Checks hardening, configurations, vulnerabilities.",
        "category": "Forensics & Analysis",
        "difficulty": "Beginner",
        "estimatedTime": "1-3min",
        "command": "lynis",
        "tags": ["audit", "hardening", "linux", "security"],
        "learnContent": "Lynis performs a comprehensive security audit of your Linux system. Checks: filesystem permissions, network configuration, installed software, user accounts, kernel parameters, and security hardening settings.",
        "params": [],
        "commandTemplate": "lynis audit system --no-colors",
    },

    # ─── CATEGORY 11: OSINT ──────────────────────────────────────────────────
    {
        "id": "whois",
        "name": "Whois",
        "description": "Domain and IP registration lookup. Owner, registrar, nameservers, dates.",
        "category": "OSINT",
        "difficulty": "Beginner",
        "estimatedTime": "2-5s",
        "command": "whois",
        "tags": ["osint", "domain", "ip", "registration"],
        "learnContent": "WHOIS queries registration databases to find who owns a domain or IP. Returns registrant contact info (often redacted), registrar, creation/expiry dates, nameservers.",
        "params": [
            {"name": "target", "label": "Domain or IP", "type": "text", "defaultValue": "", "placeholder": "example.com or 1.1.1.1", "required": True},
        ],
        "commandTemplate": "whois {target}",
    },
    {
        "id": "theharvester",
        "name": "TheHarvester",
        "description": "Gather emails, subdomains, hosts, employee names from public sources.",
        "category": "OSINT",
        "difficulty": "Beginner",
        "estimatedTime": "30s-2min",
        "command": "theHarvester",
        "tags": ["osint", "emails", "subdomains", "reconnaissance"],
        "learnContent": "TheHarvester uses search engines and public databases to collect email addresses, names, subdomains, and IP addresses related to a target domain.",
        "params": [
            {"name": "domain", "label": "Target Domain", "type": "text", "defaultValue": "", "placeholder": "example.com", "required": True},
            {"name": "sources", "label": "Data Sources", "type": "text", "defaultValue": "all", "placeholder": "all, google, bing, shodan", "required": False},
        ],
        "commandTemplate": "theHarvester -d {domain} -b {sources}",
    },
    {
        "id": "sherlock",
        "name": "Sherlock",
        "description": "Find usernames across 300+ social networks instantly.",
        "category": "OSINT",
        "difficulty": "Beginner",
        "estimatedTime": "30-120s",
        "command": "sherlock",
        "tags": ["osint", "social-media", "username", "reconnaissance"],
        "learnContent": "Sherlock checks if a username exists on hundreds of social networks and websites. Useful for tracking online presence and finding connected accounts.",
        "params": [
            {"name": "username", "label": "Username", "type": "text", "defaultValue": "", "placeholder": "johndoe", "required": True},
        ],
        "commandTemplate": "sherlock {username}",
    },
    {
        "id": "dnsrecon",
        "name": "DNSrecon",
        "description": "Full DNS enumeration: zone transfers, brute force subdomains, record types.",
        "category": "OSINT",
        "difficulty": "Intermediate",
        "estimatedTime": "30s-5min",
        "command": "dnsrecon",
        "tags": ["dns", "enumeration", "subdomains", "osint"],
        "learnContent": "DNSrecon performs comprehensive DNS enumeration: standard records, zone transfers, wildcard enumeration, reverse lookup, SRV records, and DNSSEC zone walking.",
        "params": [
            {"name": "domain", "label": "Target Domain", "type": "text", "defaultValue": "", "placeholder": "example.com", "required": True},
            {"name": "type", "label": "Scan Type", "type": "text", "defaultValue": "std", "placeholder": "std, zonewalk, axfr, brt", "required": False},
        ],
        "commandTemplate": "dnsrecon -d {domain} -t {type}",
    },

    # ─── CATEGORY 12: Vulnerability Scanning ────────────────────────────────
    {
        "id": "nuclei-vuln",
        "name": "Nuclei (Full Scan)",
        "description": "Fast template-based vulnerability scanner. 5000+ templates for CVEs and misconfigs.",
        "category": "Vulnerability Scanning",
        "difficulty": "Intermediate",
        "estimatedTime": "2-20min",
        "command": "nuclei",
        "tags": ["vulnerabilities", "cve", "templates", "scanning"],
        "learnContent": "Nuclei is a fast, customizable vulnerability scanner. Templates cover: CVEs, misconfigurations, exposed panels, default credentials, SSTI, SSRF, XSS, and more.",
        "params": [
            {"name": "target", "label": "Target", "type": "text", "defaultValue": "192.168.0.1", "placeholder": "192.168.0.x or https://target.com", "required": True},
            {"name": "templates", "label": "Template Category", "type": "text", "defaultValue": "cves,misconfig", "placeholder": "cves, misconfig, default-logins, exposed-panels", "required": False},
        ],
        "commandTemplate": "nuclei -t {templates} -u {target}",
    },
    {
        "id": "trivy",
        "name": "Trivy",
        "description": "Container and filesystem vulnerability scanner. Scan Docker images for CVEs.",
        "category": "Vulnerability Scanning",
        "difficulty": "Beginner",
        "estimatedTime": "30s-3min",
        "command": "trivy",
        "tags": ["container", "docker", "cve", "scanning"],
        "learnContent": "Trivy scans container images, filesystems, and repositories for known vulnerabilities (CVEs), misconfigurations, and secrets.",
        "params": [
            {"name": "target", "label": "Image or Path", "type": "text", "defaultValue": "ubuntu:latest", "placeholder": "ubuntu:latest or /path/to/scan", "required": True},
            {"name": "severity", "label": "Severity", "type": "text", "defaultValue": "HIGH,CRITICAL", "placeholder": "LOW,MEDIUM,HIGH,CRITICAL", "required": False},
        ],
        "commandTemplate": "trivy image --severity {severity} {target}",
    },

    # ─── CATEGORY 13: Cryptography ───────────────────────────────────────────
    {
        "id": "openssl",
        "name": "OpenSSL",
        "description": "Certificate generation, TLS testing, encryption, hash verification.",
        "category": "Cryptography",
        "difficulty": "Intermediate",
        "estimatedTime": "2-10s",
        "command": "openssl",
        "tags": ["ssl", "tls", "certificates", "encryption"],
        "learnContent": "OpenSSL is the standard cryptography toolkit. Use s_client for TLS testing, req/x509 for certs, dgst for hashing, enc for encryption.",
        "params": [
            {"name": "target", "label": "Target (host:port)", "type": "text", "defaultValue": "192.168.0.1:443", "placeholder": "host:443", "required": True},
        ],
        "commandTemplate": "openssl s_client -connect {target} -showcerts",
    },
    {
        "id": "hash-generator",
        "name": "Hash Generator",
        "description": "Generate MD5/SHA1/SHA256/SHA512/SHA3/BLAKE2 hashes of any file or text.",
        "category": "Cryptography",
        "difficulty": "Beginner",
        "estimatedTime": "1s",
        "command": "sha256sum",
        "tags": ["hash", "integrity", "checksums"],
        "learnContent": "Hash functions produce a fixed-size fingerprint of data. Use for: verifying file integrity, storing passwords, comparing data without exposing it.",
        "params": [
            {"name": "input", "label": "File or String", "type": "text", "defaultValue": "", "placeholder": "/tmp/file.txt or 'text to hash'", "required": True},
            {"name": "algorithm", "label": "Algorithm", "type": "select", "defaultValue": "sha256sum", "placeholder": None, "required": True},
        ],
        "commandTemplate": "{algorithm} {input}",
    },

    # ─── CATEGORY 14: Steganography ──────────────────────────────────────────
    {
        "id": "steghide",
        "name": "Steghide",
        "description": "Hide and extract data from JPEG/BMP/WAV/AU files using passphrase.",
        "category": "Steganography",
        "difficulty": "Beginner",
        "estimatedTime": "2-5s",
        "command": "steghide",
        "tags": ["steganography", "images", "hidden-data", "ctf"],
        "learnContent": "Steghide embeds/extracts data in image and audio files. Uses passphrase-based encryption. Very common in CTF challenges.\n\n**Extract:** `steghide extract -sf image.jpg`\n**Embed:** `steghide embed -cf image.jpg -ef secret.txt`",
        "params": [
            {"name": "action", "label": "Action", "type": "select", "defaultValue": "extract", "placeholder": None, "required": True},
            {"name": "file", "label": "Stego File", "type": "text", "defaultValue": "/tmp/image.jpg", "placeholder": "/tmp/image.jpg", "required": True},
            {"name": "passphrase", "label": "Passphrase", "type": "text", "defaultValue": "", "placeholder": "passphrase (leave empty for none)", "required": False},
        ],
        "commandTemplate": "steghide {action} -sf {file} -p '{passphrase}'",
    },
    {
        "id": "zsteg",
        "name": "Zsteg",
        "description": "Detect LSB steganography in PNG and BMP files. Used in CTF challenges.",
        "category": "Steganography",
        "difficulty": "Beginner",
        "estimatedTime": "2-10s",
        "command": "zsteg",
        "tags": ["steganography", "png", "lsb", "ctf"],
        "learnContent": "zsteg detects various steganography techniques in PNG and BMP images, including LSB encoding in different channels and bit planes.",
        "params": [
            {"name": "file", "label": "PNG/BMP File", "type": "text", "defaultValue": "/tmp/image.png", "placeholder": "/tmp/image.png", "required": True},
        ],
        "commandTemplate": "zsteg {file}",
    },

    # ─── CATEGORY 15: Reverse Engineering ────────────────────────────────────
    {
        "id": "strace",
        "name": "strace",
        "description": "Trace all system calls made by a program. See file access, network calls, process ops.",
        "category": "Reverse Engineering",
        "difficulty": "Intermediate",
        "estimatedTime": "5-60s",
        "command": "strace",
        "tags": ["reverse-engineering", "syscalls", "debugging", "tracing"],
        "learnContent": "strace intercepts and logs system calls: file open/read/write, network connect/send/recv, process fork/exec. Essential for understanding what a binary does without source code.",
        "params": [
            {"name": "binary", "label": "Binary/Command", "type": "text", "defaultValue": "/bin/ls /tmp", "placeholder": "/bin/program args", "required": True},
        ],
        "commandTemplate": "strace -e trace=file,network,process {binary}",
    },
    {
        "id": "strings-re",
        "name": "Strings + Grep",
        "description": "Extract and filter strings from binaries. Find passwords, URLs, flags.",
        "category": "Reverse Engineering",
        "difficulty": "Beginner",
        "estimatedTime": "1-5s",
        "command": "strings",
        "tags": ["reverse-engineering", "strings", "binary-analysis", "ctf"],
        "learnContent": "Extracting strings is usually the first step in reverse engineering. Piping through grep lets you filter for passwords, URLs, flags (CTF{...}), and configuration values.",
        "params": [
            {"name": "file", "label": "Binary File", "type": "text", "defaultValue": "/tmp/binary", "placeholder": "/tmp/binary", "required": True},
            {"name": "pattern", "label": "Grep Pattern", "type": "text", "defaultValue": "CTF{", "placeholder": "password|http|flag|CTF{", "required": False},
        ],
        "commandTemplate": "strings {file} | grep -i '{pattern}'",
    },
    {
        "id": "objdump",
        "name": "Objdump",
        "description": "Disassemble any binary. View assembly code, section headers, symbol table.",
        "category": "Reverse Engineering",
        "difficulty": "Advanced",
        "estimatedTime": "2-10s",
        "command": "objdump",
        "tags": ["reverse-engineering", "disassembly", "elf", "assembly"],
        "learnContent": "objdump displays information about object files and executables. Use -d to disassemble code sections, -t for symbol table, -h for section headers.",
        "params": [
            {"name": "file", "label": "Binary File", "type": "text", "defaultValue": "/tmp/binary", "placeholder": "/tmp/binary or /bin/ls", "required": True},
            {"name": "flags", "label": "Flags", "type": "text", "defaultValue": "-d", "placeholder": "-d (disassemble), -t (symbols)", "required": False},
        ],
        "commandTemplate": "objdump {flags} {file} | head -100",
    },

    # ─── CATEGORY 16: Docker & Container Security ────────────────────────────
    {
        "id": "docker-ps",
        "name": "Docker Stats",
        "description": "List all running containers with live resource usage (CPU, RAM, network).",
        "category": "Docker & Container Security",
        "difficulty": "Beginner",
        "estimatedTime": "5s",
        "command": "docker",
        "tags": ["docker", "containers", "monitoring"],
        "learnContent": "Monitoring your Docker containers lets you identify resource hogs, check health status, and spot unexpected containers that might indicate a compromise.",
        "params": [],
        "commandTemplate": "docker ps --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}\\t{{.Image}}'",
    },
    {
        "id": "docker-bench",
        "name": "Docker Bench Security",
        "description": "Run CIS Docker benchmark security audit against your Docker host.",
        "category": "Docker & Container Security",
        "difficulty": "Intermediate",
        "estimatedTime": "30-60s",
        "command": "docker-bench-security",
        "tags": ["docker", "security", "cis", "audit"],
        "learnContent": "Docker Bench Security checks your Docker host against CIS Docker Benchmark best practices: daemon configuration, container configuration, image security, and runtime security.",
        "params": [],
        "commandTemplate": "docker run --rm --net host --pid host --userns host --cap-add audit_control -v /etc:/etc:ro -v /usr/bin/containerd:/usr/bin/containerd:ro -v /usr/bin/runc:/usr/bin/runc:ro -v /usr/lib/systemd:/usr/lib/systemd:ro -v /var/lib:/var/lib:ro -v /var/run/docker.sock:/var/run/docker.sock:ro docker/docker-bench-security",
    },

    # ─── CATEGORY 17: Social Engineering ────────────────────────────────────
    {
        "id": "gophish",
        "name": "GoPhish",
        "description": "Launch GoPhish phishing campaign framework for testing your own email security.",
        "category": "Social Engineering",
        "difficulty": "Advanced",
        "estimatedTime": "Setup",
        "command": "gophish",
        "tags": ["phishing", "social-engineering", "email"],
        "learnContent": "GoPhish is an open-source phishing toolkit. Use it to: create realistic phishing emails and landing pages, track who clicks, collect credentials, measure your organization's phishing awareness.",
        "params": [],
        "commandTemplate": "/opt/gophish/gophish",
    },
    {
        "id": "qr-gen",
        "name": "QRGen",
        "description": "Generate QR codes pointing to your test URLs for QR code phishing simulation.",
        "category": "Social Engineering",
        "difficulty": "Beginner",
        "estimatedTime": "2s",
        "command": "qrencode",
        "tags": ["qr-code", "social-engineering", "phishing"],
        "learnContent": "QR code phishing (QRishing) bypasses URL-based filters. Generate a QR code pointing to your test page and see if users scan it without thinking.",
        "params": [
            {"name": "url", "label": "Target URL", "type": "text", "defaultValue": "http://192.168.0.172:8080/phish", "placeholder": "http://your-test-page.com", "required": True},
            {"name": "output", "label": "Output File", "type": "text", "defaultValue": "/tmp/qr.png", "placeholder": "/tmp/qr.png", "required": False},
        ],
        "commandTemplate": "qrencode -o {output} '{url}' && echo 'QR code saved to {output}'",
    },

    # ─── CATEGORY 18: IoT & Hardware ─────────────────────────────────────────
    {
        "id": "esp32-serial",
        "name": "ESP32 Serial Monitor",
        "description": "Connect to ESP32 via USB, view serial output in real time.",
        "category": "IoT & Hardware",
        "difficulty": "Beginner",
        "estimatedTime": "Continuous",
        "command": "picocom",
        "tags": ["esp32", "serial", "iot", "hardware"],
        "learnContent": "picocom is a minimal serial terminal. Connect to ESP32, Arduino, or any UART device. Common baud rates: 115200 (ESP32 default), 9600 (Arduino default).",
        "params": [
            {"name": "port", "label": "Serial Port", "type": "text", "defaultValue": "/dev/ttyUSB0", "placeholder": "/dev/ttyUSB0 or /dev/ttyACM0", "required": True},
            {"name": "baud", "label": "Baud Rate", "type": "text", "defaultValue": "115200", "placeholder": "115200", "required": True},
        ],
        "commandTemplate": "picocom -b {baud} {port}",
    },
    {
        "id": "flipper-info",
        "name": "Flipper Zero Info",
        "description": "Read Flipper Zero device info and battery status via USB.",
        "category": "IoT & Hardware",
        "difficulty": "Beginner",
        "estimatedTime": "5s",
        "command": "flipperzero-cli",
        "tags": ["flipper-zero", "usb", "iot"],
        "learnContent": "The Flipper Zero CLI allows scripting SubGHz operations, NFC reads, RFID operations, BadUSB payloads, and GPIO control over USB.",
        "params": [],
        "commandTemplate": "flipperzero-cli info",
    },

    # ─── CATEGORY 19: GowskiNet Specific ────────────────────────────────────
    {
        "id": "gowskinet-device-map",
        "name": "GowskiNet Device Map",
        "description": "Visual map of all 192.168.0.x devices with live status and hostname resolution.",
        "category": "GowskiNet Specific",
        "difficulty": "Beginner",
        "estimatedTime": "15-30s",
        "command": "nmap",
        "tags": ["network", "discovery", "gowskinet", "mapping"],
        "learnContent": "Scans the full 192.168.0.0/24 subnet and maps all live devices with their hostnames, MAC addresses, and open ports. Shows your network topology.",
        "params": [],
        "commandTemplate": "nmap -sn -PR --send-eth 192.168.0.0/24",
    },
    {
        "id": "cowrie-log-analyzer",
        "name": "Cowrie Log Analyzer",
        "description": "Parse and summarize Cowrie SSH honeypot logs. Top IPs, top credentials tried.",
        "category": "GowskiNet Specific",
        "difficulty": "Beginner",
        "estimatedTime": "5-15s",
        "command": "cat",
        "tags": ["honeypot", "cowrie", "logs", "analysis"],
        "learnContent": "Analyzes Cowrie log files to extract attack statistics: most common source IPs, most tried usernames and passwords, geographic distribution, attack timing patterns.",
        "params": [
            {"name": "logfile", "label": "Cowrie Log File", "type": "text", "defaultValue": "/var/log/cowrie/cowrie.log", "placeholder": "/var/log/cowrie/cowrie.log", "required": True},
        ],
        "commandTemplate": "cat {logfile} | python3 -c \"import sys,json,re; lines=sys.stdin.read().splitlines(); print('Total lines:', len(lines))\"",
    },
    {
        "id": "docker-stack",
        "name": "Docker Stack Manager",
        "description": "List all honeypot containers with their status, ports, and uptime.",
        "category": "GowskiNet Specific",
        "difficulty": "Beginner",
        "estimatedTime": "5s",
        "command": "docker",
        "tags": ["docker", "honeypot", "management"],
        "learnContent": "Manages the GowskiNet honeypot Docker stack: Cowrie, Dionaea, Conpot, Endlessh, Mailoney, Glastopf, and supporting containers like Grafana, Loki, and Prometheus.",
        "params": [],
        "commandTemplate": "docker ps -a --format 'table {{.Names}}\\t{{.Status}}\\t{{.Ports}}'",
    },
    {
        "id": "daily-report",
        "name": "Daily Report Generator",
        "description": "Generate and download a daily attack summary report from all honeypot logs.",
        "category": "GowskiNet Specific",
        "difficulty": "Beginner",
        "estimatedTime": "10-30s",
        "command": "bash",
        "tags": ["report", "honeypot", "logs", "summary"],
        "learnContent": "Aggregates attack data from all honeypots and generates a formatted daily report: total attacks, unique IPs, top credentials, attack timeline, and geographic breakdown.",
        "params": [
            {"name": "date", "label": "Date (YYYY-MM-DD)", "type": "text", "defaultValue": "today", "placeholder": "2024-01-15 or today", "required": False},
        ],
        "commandTemplate": "bash /opt/gsl/scripts/daily_report.sh {date}",
    },

    # ─── CATEGORY 20: CTF & Practice ─────────────────────────────────────────
    {
        "id": "dvwa-launch",
        "name": "DVWA",
        "description": "Launch Damn Vulnerable Web Application for local web app security practice.",
        "category": "CTF & Practice",
        "difficulty": "Beginner",
        "estimatedTime": "5s",
        "command": "docker",
        "tags": ["ctf", "dvwa", "practice", "web"],
        "learnContent": "DVWA (Damn Vulnerable Web Application) is a PHP/MySQL web app that is intentionally vulnerable. Practice SQL injection, XSS, CSRF, file upload bypasses, and more in a safe environment.",
        "params": [],
        "commandTemplate": "docker run --rm -d -p 8080:80 vulnerables/web-dvwa && echo 'DVWA starting at http://192.168.0.172:8080'",
    },
    {
        "id": "ctf-cyberchef",
        "name": "CyberChef Launcher",
        "description": "Launch CyberChef locally for encoding, decoding, encryption, and data analysis.",
        "category": "CTF & Practice",
        "difficulty": "Beginner",
        "estimatedTime": "5s",
        "command": "docker",
        "tags": ["ctf", "cyberchef", "encoding", "crypto"],
        "learnContent": "CyberChef is a web app for encoding/decoding, encryption, compression, and data analysis. Essential CTF tool. Supports base64, hex, ROT13, AES, RSA, and 400+ other operations.",
        "params": [],
        "commandTemplate": "docker run --rm -d -p 8888:8000 mpepping/cyberchef && echo 'CyberChef at http://192.168.0.172:8888'",
    },
    {
        "id": "wordlist-manager",
        "name": "Wordlist Manager",
        "description": "Download and manage wordlists: rockyou, SecLists, and custom combinations.",
        "category": "CTF & Practice",
        "difficulty": "Beginner",
        "estimatedTime": "5-60s",
        "command": "ls",
        "tags": ["wordlists", "password-cracking", "ctf"],
        "learnContent": "Good wordlists are essential for password attacks and fuzzing. SecLists is the most comprehensive collection. rockyou.txt (14M+ real passwords) is the standard benchmark.",
        "params": [],
        "commandTemplate": "ls -lh /usr/share/wordlists/ 2>/dev/null || echo 'Wordlists dir not found, install seclists'",
    },
]

# Build a lookup dict for fast access
TOOLS_BY_ID: Dict[str, Dict[str, Any]] = {tool["id"]: tool for tool in TOOLS}

CATEGORIES = sorted(list({t["category"] for t in TOOLS}))
