import React from "react";
import { useListThreats, getListThreatsQueryKey } from "@workspace/api-client-react";
import { useLocation } from "wouter";
import { Skeleton } from "@/components/ui/skeleton";
import { Shield, AlertTriangle, ClipboardCopy, ExternalLink, ChevronRight } from "lucide-react";

function generateDisclosureTemplate(threat: { name: string; description?: string | null; noveltyScore: number; mitreIds: string[]; technicalBreakdown: string; defensiveRecommendations: string }) {
  const date = new Date().toISOString().split("T")[0];
  return `# Responsible Disclosure Report
## ${threat.name}

**Reported by:** GowskiNet FORGE — Proactive Threat Research Laboratory
**Date Discovered:** ${date}
**Novelty Score:** ${threat.noveltyScore}/10 (Unprecedented)

## Executive Summary

${threat.description ?? "Novel attack technique discovered during proactive threat research."}

## Technical Details

${threat.technicalBreakdown.slice(0, 1000)}

## MITRE ATT&CK Mapping

${threat.mitreIds.map(id => `- ${id}`).join("\n")}

## Impact Assessment

This technique represents a novel attack vector with significant potential for harm if exploited by malicious actors. The estimated detection rate by existing security tooling is low.

## Remediation Recommendations

${threat.defensiveRecommendations.slice(0, 500)}

## Timeline

- ${date}: Technique discovered via automated threat research
- Disclosure: Pending vendor response

## Disclosure Policy

This report follows responsible disclosure best practices. We request a 90-day remediation window before public disclosure.

---
*Generated by GowskiNet FORGE — All research conducted for defensive purposes on authorized systems.*`;
}

function generateCveTemplate(threat: { name: string; platform: string; mitreIds: string[]; description?: string | null }) {
  return `## CVE Submission Draft

**Product:** ${threat.platform} environment
**Vulnerability Type:** Novel Attack Technique
**Severity:** High (Pending CVSS scoring)

**Description:**
A novel attack technique "${threat.name}" was discovered that may affect ${threat.platform} systems.

${threat.description ?? ""}

**MITRE ATT&CK Techniques:**
${threat.mitreIds.map(id => `- ${id}`).join("\n")}

**Affected Versions:** To be determined

**Credits:** GowskiNet FORGE Threat Research Laboratory

**Submission Notes:**
This technique was identified during proactive defensive threat research. PoC available upon request under NDA.`;
}

type Threat = {
  id: number;
  name: string;
  noveltyScore: number;
  platform: string;
  description: string | null;
  mitreIds: string[];
  technicalBreakdown: string;
  defensiveRecommendations: string;
  createdAt: string;
};

export default function Disclosure() {
  const [, navigate] = useLocation();
  const [selectedThreat, setSelectedThreat] = React.useState<Threat | null>(null);
  const [tab, setTab] = React.useState<"disclosure" | "cve" | "timeline">("disclosure");
  const [copied, setCopied] = React.useState(false);

  const params = { noveltyMin: 9, limit: 20, offset: 0 };
  const { data, isLoading } = useListThreats(params, { query: { queryKey: getListThreatsQueryKey(params) } });
  const highNoveltyThreats = (data?.threats ?? []).map(t => t as unknown as Threat);

  const copyTemplate = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const tabs = [
    { key: "disclosure" as const, label: "Disclosure" },
    { key: "cve" as const, label: "CVE Draft" },
    { key: "timeline" as const, label: "Timeline" },
  ];

  const timelineSteps = selectedThreat ? [
    { date: selectedThreat.createdAt, label: "Technique Discovered", desc: "Identified by GowskiNet FORGE during proactive research", color: '#f97316', done: true },
    { date: null, label: "Vendor Notification", desc: "Private disclosure sent to affected vendor", color: '#60a5fa', done: false },
    { date: null, label: "Acknowledgment", desc: "Vendor acknowledges receipt (target: 7 days)", color: '#7B5EA7', done: false },
    { date: null, label: "Patch Released", desc: "Vendor releases security patch", color: '#4ade80', done: false },
    { date: null, label: "Public Disclosure", desc: "Public disclosure after 90-day window", color: '#ff2d55', done: false },
  ] : [];

  return (
    <div className="p-8 max-w-7xl space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between pb-6" style={{ borderBottom: '1px solid #0f0f1a' }}>
        <div>
          <div className="flex items-center gap-3 mb-1">
            <div className="w-[3px] h-7 rounded-full" style={{ background: '#f97316', boxShadow: '0 0 8px rgba(249,115,22,0.4)' }} />
            <h1 className="text-2xl font-black tracking-tight uppercase" style={{ color: '#e2e8f0' }}>Responsible Disclosure</h1>
          </div>
          <p className="text-[11px] font-mono tracking-[0.3em] uppercase ml-4" style={{ color: '#475569' }}>
            Coordinate disclosure for unprecedented threats (novelty 9–10)
          </p>
        </div>
      </div>

      {/* Warning Banner */}
      <div
        className="flex items-start gap-4 p-5 rounded-lg"
        style={{ background: 'rgba(249,115,22,0.05)', border: '1px solid rgba(249,115,22,0.2)' }}
      >
        <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" style={{ color: '#f97316' }} />
        <div className="space-y-2">
          <div className="text-[11px] font-black tracking-wider uppercase font-mono" style={{ color: '#f97316' }}>When to Disclose</div>
          <p className="text-[11px] font-mono leading-relaxed" style={{ color: '#64748b' }}>
            If FORGE generates a technique scoring 9-10 that appears genuinely novel and exploitable in production environments, consider responsible disclosure:
          </p>
          <ul className="space-y-1 text-[11px] font-mono" style={{ color: '#64748b' }}>
            {[
              "Contact the affected vendor with a private disclosure report (90-day window)",
              "File a CVE request through MITRE or a CNA if vendor is unresponsive",
              "Document your research timeline for legal protection",
              "Only disclose publicly after vendor patches or the window expires",
            ].map((line, i) => (
              <li key={i} className="flex gap-2">
                <ChevronRight className="w-3 h-3 shrink-0 mt-0.5" style={{ color: '#f97316' }} />{line}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Qualifying Threats */}
        <div className="space-y-3">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-[3px] h-4 rounded-full" style={{ background: '#7B5EA7' }} />
            <span className="text-[10px] tracking-[0.22em] uppercase font-bold font-mono" style={{ color: '#7B5EA7' }}>Qualifying Threats (9–10)</span>
          </div>

          {isLoading ? (
            <div className="space-y-3">
              {[...Array(3)].map((_, i) => <Skeleton key={i} className="h-20 w-full rounded-lg" style={{ background: '#0a0a14' }} />)}
            </div>
          ) : highNoveltyThreats.length === 0 ? (
            <div className="p-8 text-center rounded-lg" style={{ background: '#09090f', border: '1px solid #0f0f1a' }}>
              <Shield className="w-8 h-8 mx-auto mb-2" style={{ color: '#0f0f1a' }} />
              <p className="text-[11px] font-mono" style={{ color: '#64748b' }}>No unprecedented threats generated yet.</p>
            </div>
          ) : (
            <>
              <div className="space-y-2">
                {highNoveltyThreats.map(threat => (
                  <button
                    key={threat.id}
                    onClick={() => setSelectedThreat(threat)}
                    className="w-full p-4 rounded-lg text-left transition-all"
                    style={selectedThreat?.id === threat.id
                      ? { border: '1px solid rgba(123,94,167,0.4)', background: 'rgba(123,94,167,0.06)' }
                      : { border: '1px solid #111118', background: '#0d0d1a' }
                    }
                    onMouseEnter={e => { if (selectedThreat?.id !== threat.id) (e.currentTarget as HTMLElement).style.borderColor = '#1a1a2e'; }}
                    onMouseLeave={e => { if (selectedThreat?.id !== threat.id) (e.currentTarget as HTMLElement).style.borderColor = '#111118'; }}
                  >
                    <div className="flex items-start justify-between gap-2 mb-2">
                      <div className="text-[11px] font-semibold leading-snug" style={{ color: selectedThreat?.id === threat.id ? '#a78bfa' : '#94a3b8' }}>{threat.name}</div>
                      <span
                        className="text-[9px] font-black font-mono px-2 py-0.5 rounded shrink-0 text-white"
                        style={{ background: 'linear-gradient(90deg, #7c3aed, #6d28d9)', boxShadow: '0 0 8px rgba(124,58,237,0.4)' }}
                      >
                        {threat.noveltyScore}/10
                      </span>
                    </div>
                    <div className="text-[10px] font-mono mb-2" style={{ color: '#475569' }}>{threat.platform} · {new Date(threat.createdAt).toLocaleDateString()}</div>
                    {threat.mitreIds?.length > 0 && (
                      <div className="flex flex-wrap gap-1">
                        {threat.mitreIds.slice(0, 3).map(id => (
                          <span key={id} className="text-[8px] font-mono px-1.5 py-0.5 rounded" style={{ background: 'rgba(123,94,167,0.1)', border: '1px solid rgba(123,94,167,0.2)', color: '#a78bfa' }}>{id}</span>
                        ))}
                      </div>
                    )}
                  </button>
                ))}
              </div>
              <button
                onClick={() => navigate("/threat-library")}
                className="text-[10px] font-mono font-bold"
                style={{ color: '#7B5EA7' }}
                onMouseEnter={e => (e.currentTarget.style.color = '#a78bfa')}
                onMouseLeave={e => (e.currentTarget.style.color = '#7B5EA7')}
              >
                View all in threat library →
              </button>
            </>
          )}
        </div>

        {/* Document Generator */}
        <div className="lg:col-span-2">
          {selectedThreat ? (
            <div className="rounded-lg" style={{ background: 'linear-gradient(135deg, #0e0e18 0%, #090910 100%)', border: '1px solid #111118' }}>
              <div className="flex items-center justify-between gap-3 p-5" style={{ borderBottom: '1px solid #0f0f1a' }}>
                <div>
                  <div className="text-sm font-bold" style={{ color: '#e2e8f0' }}>{selectedThreat.name}</div>
                  <div className="text-[10px] font-mono mt-0.5" style={{ color: '#475569' }}>Disclosure documentation generator</div>
                </div>
                <div className="flex gap-1">
                  {tabs.map(t => (
                    <button
                      key={t.key}
                      onClick={() => setTab(t.key)}
                      className="px-3 py-1.5 rounded text-[10px] font-mono font-bold tracking-wider uppercase transition-all"
                      style={tab === t.key
                        ? { background: 'rgba(249,115,22,0.1)', border: '1px solid rgba(249,115,22,0.3)', color: '#f97316' }
                        : { background: '#09090f', border: '1px solid #111118', color: '#64748b' }
                      }
                    >
                      {t.label}
                    </button>
                  ))}
                </div>
              </div>

              <div className="p-5 space-y-4">
                {tab === "disclosure" && (
                  <>
                    <pre className="p-4 rounded-lg text-[11px] font-mono overflow-y-auto max-h-96 whitespace-pre-wrap leading-relaxed" style={{ background: '#04040a', border: '1px solid #0a0a14', color: '#64748b' }}>
                      {generateDisclosureTemplate(selectedThreat)}
                    </pre>
                    <button
                      onClick={() => copyTemplate(generateDisclosureTemplate(selectedThreat))}
                      className="w-full flex items-center justify-center gap-2 py-2.5 rounded-lg text-[11px] font-bold tracking-wider uppercase font-mono transition-all"
                      style={{ background: '#09090f', border: '1px solid #111118', color: copied ? '#4ade80' : '#374151' }}
                      onMouseEnter={e => (e.currentTarget.style.borderColor = '#1a1a2e')}
                      onMouseLeave={e => (e.currentTarget.style.borderColor = '#111118')}
                    >
                      <ClipboardCopy className="w-3.5 h-3.5" />
                      {copied ? "Copied!" : "Copy Disclosure Template"}
                    </button>
                  </>
                )}

                {tab === "cve" && (
                  <>
                    <pre className="p-4 rounded-lg text-[11px] font-mono overflow-y-auto max-h-96 whitespace-pre-wrap leading-relaxed" style={{ background: '#04040a', border: '1px solid #0a0a14', color: '#64748b' }}>
                      {generateCveTemplate(selectedThreat)}
                    </pre>
                    <div className="flex gap-2">
                      <button
                        onClick={() => copyTemplate(generateCveTemplate(selectedThreat))}
                        className="flex-1 flex items-center justify-center gap-2 py-2.5 rounded-lg text-[11px] font-bold tracking-wider uppercase font-mono transition-all"
                        style={{ background: '#09090f', border: '1px solid #111118', color: copied ? '#4ade80' : '#374151' }}
                      >
                        <ClipboardCopy className="w-3.5 h-3.5" />
                        {copied ? "Copied!" : "Copy CVE Template"}
                      </button>
                      <button
                        onClick={() => window.open("https://cveform.mitre.org/", "_blank")}
                        className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-[11px] font-bold tracking-wider uppercase font-mono"
                        style={{ background: '#09090f', border: '1px solid #111118', color: '#64748b' }}
                        onMouseEnter={e => (e.currentTarget.style.borderColor = '#1a1a2e')}
                        onMouseLeave={e => (e.currentTarget.style.borderColor = '#111118')}
                      >
                        <ExternalLink className="w-3.5 h-3.5" />MITRE CVE Form
                      </button>
                    </div>
                  </>
                )}

                {tab === "timeline" && (
                  <div className="space-y-0">
                    {timelineSteps.map((step, i) => (
                      <div key={i} className="flex gap-4">
                        <div className="flex flex-col items-center">
                          <div
                            className="w-3 h-3 rounded-full shrink-0 mt-0.5"
                            style={step.done
                              ? { background: step.color, boxShadow: `0 0 6px ${step.color}60` }
                              : { background: '#0f0f1a', border: `1px solid #1a1a2e` }
                            }
                          />
                          {i < timelineSteps.length - 1 && (
                            <div className="w-px flex-1 mt-1 mb-1" style={{ background: '#111118' }} />
                          )}
                        </div>
                        <div className="pb-5">
                          <div className="text-[11px] font-bold mb-0.5" style={{ color: step.done ? step.color : '#374151' }}>{step.label}</div>
                          <div className="text-[10px] font-mono" style={{ color: '#475569' }}>
                            {step.date ? new Date(step.date).toLocaleDateString() : "Pending"}
                          </div>
                          <div className="text-[10px] font-mono mt-0.5" style={{ color: '#64748b' }}>{step.desc}</div>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ) : (
            <div
              className="h-full min-h-64 flex items-center justify-center rounded-lg"
              style={{ background: '#09090f', border: '1px solid #0f0f1a' }}
            >
              <div className="text-center">
                <Shield className="w-10 h-10 mx-auto mb-3" style={{ color: '#0f0f1a' }} />
                <p className="text-sm font-mono" style={{ color: '#64748b' }}>Select a qualifying threat to generate disclosure documentation.</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
