---
efiSystemPartition: "/boot/efi"
userSwapChoices: [none, small, suspend, file]
defaultFileSystemType: "ext4"
availableFileSystemTypes: ["ext4", "btrfs", "xfs", "f2fs"]
swapPartitionName: swap
ensureSuspendToDisk: true
neverCreateSwap: false
