---
services:
  - name: NetworkManager
  - name: bluetooth
  - name: sddm
  - name: cups
  - name: avahi-daemon
  - name: chronyd
  - name: firewalld
  - name: earlyoom
  - name: irqbalance
  - name: systemd-zram-setup@zram0
  - name: fstrim.timer
  - name: paccache.timer
  - name: reflector.timer
  - name: nyxus-firstboot
targets:
  - name: graphical.target
