---
defaultGroups: [wheel, audio, video, network, storage, input, lp, scanner]
autologinGroup: autologin
sudoersGroup: wheel
setRootPassword: true
doAutologin: false
passwordRequirements:
  minLength: -1
  maxLength: -1
