# NYXUS · Calamares welcome module
---
showSupportUrl:      true
showKnownIssuesUrl:  true
showReleaseNotesUrl: true

requirements:
    requiredStorage:   12.0
    requiredRam:       2.0
    internetCheckUrl:  https://archlinux.org

    check:
      - storage
      - ram
      - power
      - internet
      - root
      - screen

    required:
      - storage
      - ram
      - root
