uploads = []

[[generated]]
id = "I7jH3PnwgE8xELBRJPrZu"
uri = "file://artifacts/nyxus-web/public/nyxus-bg.png"
type = "image"
title = "nyxus hacker ascii background"

[[generated]]
id = "hCTP2IM5H7O376qlXB17U"
uri = "file://artifacts/nyxus-web/public/nyxus-wallpaper.png"
type = "image"
title = "nyxus hacker neon blacklight UV scene wallpaper"

[[outputs]]
id = "jM4hqh5aV4f7WaZ9t_iQZ"
uri = "file://artifacts/nyxus-web/public/nyxus-wallpaper.png"
type = "image"
title = "NYXUS Wallpaper v3 — nyxus-wallpaper.png"
