import React from "react";
import { Link, useLocation } from "wouter";
import { useGetDashboardStats, useGetSettings, useUpdateSettings } from "@workspace/api-client-react";
import { Flame, Shield, Database, List, Brain, TestTube, Crosshair, BookOpen, Settings, Activity, ShieldAlert, Cpu, ChevronRight, LogOut } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { useAuth } from "@/lib/auth";

export function Layout({ children }: { children: React.ReactNode }) {
  const [location] = useLocation();
  const { data: stats } = useGetDashboardStats();
  const { data: settings } = useGetSettings();
  const updateSettings = useUpdateSettings();
  const { user, logout } = useAuth();

  const [disclaimerOpen, setDisclaimerOpen] = React.useState(false);
  const [disclaimerChecked, setDisclaimerChecked] = React.useState(false);

  React.useEffect(() => {
    if (settings && !settings.disclaimerAccepted) {
      setDisclaimerOpen(true);
    }
  }, [settings]);

  const acceptDisclaimer = () => {
    if (disclaimerChecked) {
      updateSettings.mutate({ data: { disclaimerAccepted: true } });
      setDisclaimerOpen(false);
    }
  };

  const navItems = [
    { href: "/", label: "Dashboard", icon: Activity },
    { href: "/input-lab", label: "Input Lab", icon: Database },
    { href: "/mutation-lab", label: "Mutation Lab", icon: TestTube },
    { href: "/threat-library", label: "Threat Library", icon: List },
    { href: "/detection-rules", label: "Detection Rules", icon: ShieldAlert },
    { href: "/notes", label: "Research Notes", icon: BookOpen },
    { href: "/knowledge-base", label: "Knowledge Base", icon: Brain },
    { href: "/redforge", label: "REDFORGE", icon: Crosshair },
    { href: "/meli", label: "Meli C2", icon: Cpu },
    { href: "/disclosure", label: "Disclosure", icon: Shield },
    { href: "/settings", label: "Settings", icon: Settings },
  ];

  return (
    <div className="flex h-screen w-full overflow-hidden" style={{ background: '#070710' }}>
      <Dialog open={disclaimerOpen} onOpenChange={setDisclaimerOpen}>
        <DialogContent className="sm:max-w-lg border-0 shadow-2xl" style={{ background: '#0d0d1a', border: '1px solid #1e1e30' }}>
          <DialogHeader>
            <DialogTitle className="text-red-400 font-black text-lg flex items-center gap-2 tracking-widest uppercase">
              <div className="w-2 h-2 rounded-full bg-red-500 animate-pulse" />
              Restricted System
            </DialogTitle>
            <DialogDescription className="pt-4 leading-relaxed font-mono text-sm" style={{ color: '#64748b' }}>
              GowskiNet FORGE is a proactive threat generation and research laboratory.
              The techniques and code generated by this system are strictly for defensive
              research and authorized penetration testing.
              <br /><br />
              <span style={{ color: '#f97316' }}>Unauthorized use is a federal offense.</span> All sessions are logged.
            </DialogDescription>
          </DialogHeader>
          <div className="flex items-start gap-3 py-4 px-4 rounded-lg" style={{ background: '#0a0a15', border: '1px solid #1e1e30' }}>
            <Checkbox
              id="terms"
              checked={disclaimerChecked}
              onCheckedChange={(c) => setDisclaimerChecked(c as boolean)}
              className="mt-0.5"
            />
            <label htmlFor="terms" className="text-sm font-mono leading-relaxed cursor-pointer" style={{ color: '#94a3b8' }}>
              I confirm all research is conducted for defensive purposes on authorized systems only.
            </label>
          </div>
          <DialogFooter>
            <Button
              onClick={acceptDisclaimer}
              disabled={!disclaimerChecked}
              className="w-full font-black tracking-widest uppercase forge-glow-btn"
              style={{
                background: disclaimerChecked ? '#f97316' : '#1a1a2e',
                color: disclaimerChecked ? 'white' : '#374151',
                border: 'none',
                letterSpacing: '0.15em'
              }}
            >
              Acknowledge and Enter
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Sidebar */}
      <aside
        className="w-64 flex flex-col h-full shrink-0 relative"
        style={{ background: '#050509', borderRight: '1px solid #111118' }}
      >
        {/* Top orange accent line */}
        <div style={{ height: '2px', background: 'linear-gradient(90deg, #f97316 0%, #f9731630 60%, transparent 100%)' }} />

        {/* Logo */}
        <div className="px-6 py-5" style={{ borderBottom: '1px solid #0f0f1a' }}>
          <div className="flex items-center gap-2">
            <div className="flex items-center gap-1.5">
              <div className="w-1.5 h-5 rounded-full" style={{ background: '#f97316', boxShadow: '0 0 8px rgba(249,115,22,0.6)' }} />
              <span className="font-black tracking-widest uppercase text-lg" style={{ color: '#f97316', letterSpacing: '0.12em' }}>FORGE</span>
            </div>
            <span className="text-xs font-medium tracking-wider" style={{ color: '#2d2d3e' }}>by GowskiNet</span>
          </div>
          <div className="flex items-center gap-1.5 mt-1.5 ml-3">
            <span className="text-[9px] tracking-[0.3em] uppercase font-mono" style={{ color: '#1e1e2e' }}>Threat Research Platform</span>
          </div>
        </div>

        {/* Navigation */}
        <nav className="flex-1 overflow-y-auto py-3 px-3 space-y-0.5">
          {navItems.map((item) => {
            const isActive = location === item.href || (item.href !== "/" && location.startsWith(item.href));
            return (
              <Link
                key={item.href}
                href={item.href}
                className="flex items-center gap-3 px-3 py-2.5 rounded-md transition-all duration-150 group relative"
                style={isActive ? {
                  background: 'linear-gradient(90deg, rgba(249,115,22,0.12) 0%, rgba(249,115,22,0.04) 100%)',
                  borderLeft: '2px solid #f97316',
                  paddingLeft: '10px',
                } : {
                  borderLeft: '2px solid transparent',
                }}
              >
                {isActive && (
                  <div className="absolute inset-0 rounded-md" style={{ background: 'rgba(249,115,22,0.03)' }} />
                )}
                <item.icon
                  className="w-3.5 h-3.5 shrink-0 relative z-10"
                  style={{ color: isActive ? '#f97316' : '#2a2a3e' }}
                />
                <span
                  className="text-[11px] tracking-[0.12em] uppercase font-bold relative z-10"
                  style={{ color: isActive ? '#f97316' : '#2e2e42', transition: 'color 0.15s' }}
                >
                  {item.label}
                </span>
                {item.href === "/meli" && (stats?.unanalyzedMeliCommands ?? 0) > 0 && (
                  <span
                    className="ml-auto text-[9px] font-black px-1.5 py-0.5 rounded-full z-10 relative"
                    style={{ background: '#f97316', color: 'white', boxShadow: '0 0 8px rgba(249,115,22,0.5)' }}
                  >
                    {stats!.unanalyzedMeliCommands}
                  </span>
                )}
              </Link>
            );
          })}
        </nav>

        {/* Footer */}
        <div className="px-5 py-4 space-y-3" style={{ borderTop: '1px solid #0f0f1a' }}>
          <div className="flex items-center justify-between gap-2">
            <div className="flex items-center gap-2 min-w-0">
              <Shield className="w-3 h-3 shrink-0" style={{ color: '#2a2a3e' }} />
              <span className="text-[10px] font-mono truncate" style={{ color: '#475569' }}>
                {user?.username ?? "—"}
              </span>
            </div>
            <button
              onClick={() => { void logout(); }}
              title="Sign out"
              className="flex items-center gap-1 text-[9px] tracking-[0.15em] uppercase font-bold font-mono transition-colors"
              style={{ color: '#475569' }}
              onMouseEnter={(e) => (e.currentTarget.style.color = '#ff2d55')}
              onMouseLeave={(e) => (e.currentTarget.style.color = '#475569')}
            >
              <LogOut className="w-3 h-3" />Sign Out
            </button>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-1.5 h-1.5 rounded-full animate-forge-pulse" style={{ background: '#ef4444', boxShadow: '0 0 6px rgba(239,68,68,0.6)' }} />
            <span className="text-[9px] tracking-[0.25em] uppercase font-bold font-mono" style={{ color: '#1e1e2e' }}>
              Restricted Research System
            </span>
          </div>
        </div>
      </aside>

      {/* Main content */}
      <main className="flex-1 h-full overflow-y-auto" style={{ background: '#070710' }}>
        {children}
      </main>
    </div>
  );
}
