# NYXUS · systemd-resolved DNS hardening · rev 2026-05-13 r1
[Resolve]
DNS=1.1.1.1#cloudflare-dns.com 9.9.9.9#dns.quad9.net
FallbackDNS=8.8.8.8#dns.google 8.8.4.4#dns.google
DNSSEC=allow-downgrade
DNSOverTLS=opportunistic
Cache=yes
ReadEtcHosts=yes
