export const DISCLAIMER_TEXT = `# GowskiNet REDFORGE — Legal Disclaimer

GowskiNet REDFORGE is a personal cybersecurity training and research tool designed exclusively for use on networks and systems you own or have explicit written authorization to test. All attack simulations generated by this tool are intended solely for defensive security education, threat hunting practice, and personal skill development on isolated home lab infrastructure.

Unauthorized use of attack tools against networks, systems, or devices you do not own is illegal under the Computer Fraud and Abuse Act (CFAA), the UK Computer Misuse Act, and equivalent laws in most jurisdictions worldwide. The operator of this tool is solely responsible for ensuring all use is lawful and authorized.

This tool is not intended for offensive use, criminal activity, or testing against any system without explicit written permission. By using REDFORGE you confirm that all targets are on your own network at 192.168.0.x and that you own or are explicitly authorized to test every device on that network.

For educational and authorized security research purposes only.`;