# NYXUS · NetworkManager defaults · rev 2026-05-13 r1
[main]
dns=systemd-resolved
rc-manager=symlink
plugins=keyfile

[connection]
# Random per-connection MAC for Wi-Fi (privacy).
wifi.cloned-mac-address=stable
wifi.mac-address-randomization=2
ethernet.cloned-mac-address=preserve

[device]
wifi.scan-rand-mac-address=yes
