#!/usr/bin/env bash
# ============================================
# NYXUS
# Copyright © 2026 Joseph A. Sierengowski
# All Rights Reserved
# Unauthorized use or distribution prohibited
# NYX-J5W-2026-SIERENGOWSKI-LOCKED
# ============================================
#
# archiso profile definition for the NYX ISO.
# See: https://wiki.archlinux.org/title/Archiso

iso_name="nyxus"
iso_label="NYXUS_2026_07"
iso_publisher="Joseph A. Sierengowski <https://github.com/sierengowski/NyX.OS-V1>"
iso_application="NYXUS Live/Install"
iso_version="2026.07.22"
install_dir="arch"
buildmodes=('iso')
bootmodes=(
  'bios.syslinux'
  'uefi.grub'
)
arch="x86_64"
pacman_conf="pacman.conf"
airootfs_image_type="squashfs"
# ── SQUASHFS COMPRESSION — zstd, NOT xz (changed 2026-07-30) ─────────────────
# archiso's stock releng profile uses xz, and so did every NYXUS ISO up to and
# including 2026.07.29. That default is written for a ~1GB installer image.
# NYXUS's airootfs is 7.3GB, and xz decode cost is paid on EVERY cold read for
# the whole life of the live session.
#
# MEASURED on this builder box, same 2140MB of the real 07.29 image
# (/usr/bin + /usr/lib/systemd), single-threaded unsquashfs, warm page cache
# so USB I/O is excluded and only decode cost is compared:
#
#     -comp xz  -Xbcj x86 -b 1M -Xdict-size 1M   647.0 MB   29.5 s   ( 72 MB/s)
#     -comp zstd -Xcompression-level 19 -b 1M    716.7 MB    3.9 s   (549 MB/s)
#
# => 7.6x faster reads for +10.8% image size (whole ISO ~8.06GB -> ~8.9GB).
# Per 1MiB squashfs block that is ~14.5ms of CPU under xz vs ~1.9ms under zstd,
# and squashfs must inflate a WHOLE block to serve a single 4KiB read — so a
# desktop session start, which touches thousands of scattered small files,
# spends most of its time inflating. This is the dominant cause of the "eww
# takes minutes to appear / everything loads slowly" reports on the 07.29 stick.
#
# To bake the old xz image: `sudo NYX_SQUASH_COMP=xz ./build-iso.sh`
# (build-iso.sh rewrites this line in the staged profile copy).
airootfs_image_tool_options=('-comp' 'zstd' '-Xcompression-level' '19' '-b' '1M')
bootstrap_tarball_compression=(zstd -c -T0 --auto-threads=logical --long -19)
file_permissions=(
  # ── GENERATED — do not hand-edit the 0:0:755 block ────────────────────────
  # Regenerate with:  iso-builder/regen-file-permissions.py
  # build-iso.sh also regenerates this in the throwaway profile copy after
  # staging, so bake-time-only files are covered. archiso copies airootfs with
  # --no-preserve=mode, so anything executable that is missing here ships 644
  # and silently cannot run.
  #
  # Entries above the generated block are hand-pinned (non-755 modes and
  # directories) and are preserved by the regenerator.
  ["/etc/nyxus"]="0:0:755"
  ["/etc/sudoers.d/10-nyxus-live"]="0:0:440"
  ["/root"]="0:0:750"
  ["/usr/local/bin/jeTT"]="0:0:755"

  ["/etc/grub.d/41_nyxus_recovery"]="0:0:755"
  ["/etc/nyxus-firstboot.d/01-machine-id.sh"]="0:0:755"
  ["/etc/nyxus-firstboot.d/02-xdg-user-dirs.sh"]="0:0:755"
  ["/etc/nyxus-firstboot.d/03-mime-defaults.sh"]="0:0:755"
  ["/etc/nyxus-firstboot.d/04-welcome.sh"]="0:0:755"
  ["/etc/nyxus-firstboot.d/05-icon-cache.sh"]="0:0:755"
  ["/etc/nyxus-firstboot.d/06-honeypot-stack.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/app-rail.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/arsenal-feed.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/audio-action.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/audio-sinks.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/audio.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/bar-tiles.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/battery.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/bluetooth.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/brightness.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/bt-action.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/bt-list.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/calendar-month.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/calendar.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/cava.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/comet.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/compile-eww-css.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/cpu-bars.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/deepcore.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/disk-info.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/dock-action.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/dock-drop.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/dock-enrich-icons.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/dock-menu.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/dock-preview.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/dock-stack.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/dock-state.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/fan-graph.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/fan-strip.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/fog-swirl.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/forge-feed.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/gen-cosmic-flyout-assets.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/gen-fog-texture.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/gen-graffiti-assets.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/gen-mascot-sprites.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/gen-starfield-lock.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/gen-starlight-assets.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/ghost-feed.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/hotkey-cheatsheet.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/hub-apps-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/lab-feed.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/mascot.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/mesh-feed.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/mic.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/mission-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/moon.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/neon-flicker.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/net-graph.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/net-strip.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/network.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/notif-action.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/notif-history.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/notif-mute.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/notifications.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/osd-capslock.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/osd-show.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/overlay-shield.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/pill-rim.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/pill-shimmer.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/player.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/power-profile.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/prism-anim.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/qs-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/quicksettings-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/quicksettings.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/random-glow.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/security-state.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/sense-poll.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/snap-picker-toggle.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/snap-toast.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/starfield-lock-anim.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/starfield-lock-reveal.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/starlight-anim.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/start-feed.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/start-search.py"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/startmenu-apps.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/sys-graph.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/sys-pulse.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/taskbar.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/ticker.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/time.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/updates-list.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/updates.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/weather.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/wifi-action.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/wifi-list.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/wifi-saved.sh"]="0:0:755"
  ["/etc/skel/.config/eww/scripts/workspaces.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/nyxus-daily-line.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/nyxus-idle-glass.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/nyxus-lens.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/nyxus-prism-pulse.sh"]="0:0:755"
  ["/etc/skel/.config/hypr/scripts/nyxus-pulse.sh"]="0:0:755"
  ["/etc/skel/.config/nyxus/nyxus-home/main.py"]="0:0:755"
  ["/etc/skel/.config/nyxus/nyxus_matrix_saver.py"]="0:0:755"
  ["/etc/skel/.config/nyxus/nyxus_palette.py"]="0:0:755"
  ["/etc/skel/.config/nyxus/nyxus_screensaver.py"]="0:0:755"
  ["/etc/skel/.config/rofi/apps-launcher.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/cheatsheet.sh"]="0:0:755"
  ["/etc/skel/.config/rofi/power.sh"]="0:0:755"
  ["/etc/skel/Arsenal/setup-apps.sh"]="0:0:755"
  ["/etc/skel/Desktop/install-nyxus.desktop"]="0:0:755"
  ["/opt/arsenal/tools/Forge/forge"]="0:0:755"
  ["/opt/arsenal/tools/GSL/gsl-backend/start.sh"]="0:0:755"
  ["/opt/arsenal/tools/axiom/meli/scripts/cowrie_to_meli.py"]="0:0:755"
  ["/opt/arsenal/tools/axiom/meli/scripts/deploy_cowrie_forwarder.sh"]="0:0:755"
  ["/opt/arsenal/tools/axiom/meli/scripts/deploy_http_honeypot.sh"]="0:0:755"
  ["/opt/arsenal/tools/axiom/meli/scripts/meli_http_honeypot.py"]="0:0:755"
  ["/opt/arsenal/tools/axiom/meli/uninstall.sh"]="0:0:755"
  ["/opt/arsenal/tools/c2/implant/implant"]="0:0:755"
  ["/opt/arsenal/tools/c2/redirector/redirector"]="0:0:755"
  ["/opt/arsenal/tools/c2/teamserver/teamserver"]="0:0:755"
  ["/opt/meli/app/install.sh"]="0:0:755"
  ["/opt/meli/app/uninstall.sh"]="0:0:755"
  ["/opt/nyxus/nyxus_powermenu.py"]="0:0:755"
  ["/opt/nyxus/nyxus_screensaver.py"]="0:0:755"
  ["/opt/nyxus/nyxus_settings.py"]="0:0:755"
  ["/opt/nyxus/nyxus_welcome_note.py"]="0:0:755"
  ["/root/customize_airootfs.sh"]="0:0:755"
  ["/usr/bin/bifrost"]="0:0:755"
  ["/usr/bin/bifrost-guardian"]="0:0:755"
  ["/usr/local/bin/arsenal"]="0:0:755"
  ["/usr/local/bin/arsenal-hub"]="0:0:755"
  ["/usr/local/bin/axiom"]="0:0:755"
  ["/usr/local/bin/jett"]="0:0:755"
  ["/usr/local/bin/meli"]="0:0:755"
  ["/usr/local/bin/nyxus"]="0:0:755"
  ["/usr/local/bin/nyxus-accent-from-wallpaper"]="0:0:755"
  ["/usr/local/bin/nyxus-account"]="0:0:755"
  ["/usr/local/bin/nyxus-app-shell"]="0:0:755"
  ["/usr/local/bin/nyxus-apply-accent"]="0:0:755"
  ["/usr/local/bin/nyxus-backdoor-log"]="0:0:755"
  ["/usr/local/bin/nyxus-backup"]="0:0:755"
  ["/usr/local/bin/nyxus-bar-plugins"]="0:0:755"
  ["/usr/local/bin/nyxus-battery"]="0:0:755"
  ["/usr/local/bin/nyxus-bd-detect"]="0:0:755"
  ["/usr/local/bin/nyxus-bd-router"]="0:0:755"
  ["/usr/local/bin/nyxus-beat"]="0:0:755"
  ["/usr/local/bin/nyxus-beatd"]="0:0:755"
  ["/usr/local/bin/nyxus-blackarch-full"]="0:0:755"
  ["/usr/local/bin/nyxus-boot-check"]="0:0:755"
  ["/usr/local/bin/nyxus-bootstrap"]="0:0:755"
  ["/usr/local/bin/nyxus-c2"]="0:0:755"
  ["/usr/local/bin/nyxus-clipboard"]="0:0:755"
  ["/usr/local/bin/nyxus-companion"]="0:0:755"
  ["/usr/local/bin/nyxus-consoles"]="0:0:755"
  ["/usr/local/bin/nyxus-context-menu.sh"]="0:0:755"
  ["/usr/local/bin/nyxus-control"]="0:0:755"
  ["/usr/local/bin/nyxus-crash-report"]="0:0:755"
  ["/usr/local/bin/nyxus-crashd"]="0:0:755"
  ["/usr/local/bin/nyxus-desktop"]="0:0:755"
  ["/usr/local/bin/nyxus-distrobox-helper"]="0:0:755"
  ["/usr/local/bin/nyxus-dock"]="0:0:755"
  ["/usr/local/bin/nyxus-doctor"]="0:0:755"
  ["/usr/local/bin/nyxus-doh"]="0:0:755"
  ["/usr/local/bin/nyxus-dream"]="0:0:755"
  ["/usr/local/bin/nyxus-drop"]="0:0:755"
  ["/usr/local/bin/nyxus-dynamic-wallpaper.sh"]="0:0:755"
  ["/usr/local/bin/nyxus-edr-repair"]="0:0:755"
  ["/usr/local/bin/nyxus-eww-cinematic"]="0:0:755"
  ["/usr/local/bin/nyxus-eww-launch"]="0:0:755"
  ["/usr/local/bin/nyxus-eww-launch-safe"]="0:0:755"
  ["/usr/local/bin/nyxus-files"]="0:0:755"
  ["/usr/local/bin/nyxus-focusmode"]="0:0:755"
  ["/usr/local/bin/nyxus-freeform"]="0:0:755"
  ["/usr/local/bin/nyxus-gamemode"]="0:0:755"
  ["/usr/local/bin/nyxus-gen-backdrop"]="0:0:755"
  ["/usr/local/bin/nyxus-ghost"]="0:0:755"
  ["/usr/local/bin/nyxus-ghost-auth"]="0:0:755"
  ["/usr/local/bin/nyxus-ghost-helper"]="0:0:755"
  ["/usr/local/bin/nyxus-ghost-register"]="0:0:755"
  ["/usr/local/bin/nyxus-glow"]="0:0:755"
  ["/usr/local/bin/nyxus-godsapp"]="0:0:755"
  ["/usr/local/bin/nyxus-graffiti-wall"]="0:0:755"
  ["/usr/local/bin/nyxus-greeter"]="0:0:755"
  ["/usr/local/bin/nyxus-hacker-mode"]="0:0:755"
  ["/usr/local/bin/nyxus-home"]="0:0:755"
  ["/usr/local/bin/nyxus-home-deck"]="0:0:755"
  ["/usr/local/bin/nyxus-honeypot-firewall"]="0:0:755"
  ["/usr/local/bin/nyxus-hotkey"]="0:0:755"
  ["/usr/local/bin/nyxus-hub-apps"]="0:0:755"
  ["/usr/local/bin/nyxus-hub-close"]="0:0:755"
  ["/usr/local/bin/nyxus-hub-launch"]="0:0:755"
  ["/usr/local/bin/nyxus-hub-open"]="0:0:755"
  ["/usr/local/bin/nyxus-hub-search"]="0:0:755"
  ["/usr/local/bin/nyxus-install"]="0:0:755"
  ["/usr/local/bin/nyxus-intel"]="0:0:755"
  ["/usr/local/bin/nyxus-journal-ship"]="0:0:755"
  ["/usr/local/bin/nyxus-kernel-switch"]="0:0:755"
  ["/usr/local/bin/nyxus-launcher"]="0:0:755"
  ["/usr/local/bin/nyxus-lens"]="0:0:755"
  ["/usr/local/bin/nyxus-live-wallpaper"]="0:0:755"
  ["/usr/local/bin/nyxus-livewall-flagship"]="0:0:755"
  ["/usr/local/bin/nyxus-livewall-generate"]="0:0:755"
  ["/usr/local/bin/nyxus-living"]="0:0:755"
  ["/usr/local/bin/nyxus-lock-art"]="0:0:755"
  ["/usr/local/bin/nyxus-lock-cava"]="0:0:755"
  ["/usr/local/bin/nyxus-lock-track"]="0:0:755"
  ["/usr/local/bin/nyxus-loginscreen"]="0:0:755"
  ["/usr/local/bin/nyxus-mac-randomize"]="0:0:755"
  ["/usr/local/bin/nyxus-mission"]="0:0:755"
  ["/usr/local/bin/nyxus-mission-control-toggle"]="0:0:755"
  ["/usr/local/bin/nyxus-mood"]="0:0:755"
  ["/usr/local/bin/nyxus-netusage"]="0:0:755"
  ["/usr/local/bin/nyxus-notepad"]="0:0:755"
  ["/usr/local/bin/nyxus-notes"]="0:0:755"
  ["/usr/local/bin/nyxus-notif-to-eww"]="0:0:755"
  ["/usr/local/bin/nyxus-notifications"]="0:0:755"
  ["/usr/local/bin/nyxus-nowplaying"]="0:0:755"
  ["/usr/local/bin/nyxus-oath-register"]="0:0:755"
  ["/usr/local/bin/nyxus-overlay-open"]="0:0:755"
  ["/usr/local/bin/nyxus-pacman-toast"]="0:0:755"
  ["/usr/local/bin/nyxus-palette-extract"]="0:0:755"
  ["/usr/local/bin/nyxus-panic"]="0:0:755"
  ["/usr/local/bin/nyxus-passwords"]="0:0:755"
  ["/usr/local/bin/nyxus-persist-login"]="0:0:755"
  ["/usr/local/bin/nyxus-plugins"]="0:0:755"
  ["/usr/local/bin/nyxus-plymouth"]="0:0:755"
  ["/usr/local/bin/nyxus-plymouth-install"]="0:0:755"
  ["/usr/local/bin/nyxus-postinstall"]="0:0:755"
  ["/usr/local/bin/nyxus-powermenu"]="0:0:755"
  ["/usr/local/bin/nyxus-protonup"]="0:0:755"
  ["/usr/local/bin/nyxus-pulsed"]="0:0:755"
  ["/usr/local/bin/nyxus-qs"]="0:0:755"
  ["/usr/local/bin/nyxus-record"]="0:0:755"
  ["/usr/local/bin/nyxus-rotate-walls"]="0:0:755"
  ["/usr/local/bin/nyxus-sage"]="0:0:755"
  ["/usr/local/bin/nyxus-screensaver"]="0:0:755"
  ["/usr/local/bin/nyxus-screenshot"]="0:0:755"
  ["/usr/local/bin/nyxus-secboot"]="0:0:755"
  ["/usr/local/bin/nyxus-security"]="0:0:755"
  ["/usr/local/bin/nyxus-sense"]="0:0:755"
  ["/usr/local/bin/nyxus-session-start"]="0:0:755"
  ["/usr/local/bin/nyxus-set-wallpaper"]="0:0:755"
  ["/usr/local/bin/nyxus-set-wallpaper.sh"]="0:0:755"
  ["/usr/local/bin/nyxus-settings"]="0:0:755"
  ["/usr/local/bin/nyxus-setup-apps"]="0:0:755"
  ["/usr/local/bin/nyxus-sfx"]="0:0:755"
  ["/usr/local/bin/nyxus-shader"]="0:0:755"
  ["/usr/local/bin/nyxus-shield"]="0:0:755"
  ["/usr/local/bin/nyxus-snap"]="0:0:755"
  ["/usr/local/bin/nyxus-sound"]="0:0:755"
  ["/usr/local/bin/nyxus-sound-bake"]="0:0:755"
  ["/usr/local/bin/nyxus-sound-forge"]="0:0:755"
  ["/usr/local/bin/nyxus-sound.sh"]="0:0:755"
  ["/usr/local/bin/nyxus-soundd"]="0:0:755"
  ["/usr/local/bin/nyxus-sounds"]="0:0:755"
  ["/usr/local/bin/nyxus-spray"]="0:0:755"
  ["/usr/local/bin/nyxus-stage-system-walls"]="0:0:755"
  ["/usr/local/bin/nyxus-start"]="0:0:755"
  ["/usr/local/bin/nyxus-stickies"]="0:0:755"
  ["/usr/local/bin/nyxus-store"]="0:0:755"
  ["/usr/local/bin/nyxus-store-install"]="0:0:755"
  ["/usr/local/bin/nyxus-studio"]="0:0:755"
  ["/usr/local/bin/nyxus-supernova"]="0:0:755"
  ["/usr/local/bin/nyxus-suricata-setup"]="0:0:755"
  ["/usr/local/bin/nyxus-sync-stations"]="0:0:755"
  ["/usr/local/bin/nyxus-sysmon"]="0:0:755"
  ["/usr/local/bin/nyxus-terminal"]="0:0:755"
  ["/usr/local/bin/nyxus-threatd"]="0:0:755"
  ["/usr/local/bin/nyxus-tint"]="0:0:755"
  ["/usr/local/bin/nyxus-tintd"]="0:0:755"
  ["/usr/local/bin/nyxus-tour"]="0:0:755"
  ["/usr/local/bin/nyxus-updater"]="0:0:755"
  ["/usr/local/bin/nyxus-usbguard-helper"]="0:0:755"
  ["/usr/local/bin/nyxus-usbwatch-event"]="0:0:755"
  ["/usr/local/bin/nyxus-virt-setup"]="0:0:755"
  ["/usr/local/bin/nyxus-voice"]="0:0:755"
  ["/usr/local/bin/nyxus-voice-install"]="0:0:755"
  ["/usr/local/bin/nyxus-voice-model"]="0:0:755"
  ["/usr/local/bin/nyxus-voiced"]="0:0:755"
  ["/usr/local/bin/nyxus-vpn"]="0:0:755"
  ["/usr/local/bin/nyxus-wait-bootstrap"]="0:0:755"
  ["/usr/local/bin/nyxus-wall-cycle"]="0:0:755"
  ["/usr/local/bin/nyxus-wall-fx"]="0:0:755"
  ["/usr/local/bin/nyxus-wall-next"]="0:0:755"
  ["/usr/local/bin/nyxus-wallpaper-autostart"]="0:0:755"
  ["/usr/local/bin/nyxus-wallpaper-studio"]="0:0:755"
  ["/usr/local/bin/nyxus-weather"]="0:0:755"
  ["/usr/local/bin/nyxus-weather-line"]="0:0:755"
  ["/usr/local/bin/nyxus-webapp"]="0:0:755"
  ["/usr/local/bin/nyxus-welcome"]="0:0:755"
  ["/usr/local/bin/nyxus-welcome-helper"]="0:0:755"
  ["/usr/local/bin/nyxus-welcome-note"]="0:0:755"
  ["/usr/local/bin/nyxus-whispers"]="0:0:755"
  ["/usr/local/bin/nyxus-workspace-wallpaperd"]="0:0:755"
  ["/usr/local/bin/scripts/jett-ctl.sh"]="0:0:755"
  ["/usr/local/bin/sharkdash_core.py"]="0:0:755"
  ["/usr/local/bin/sharkdash_health.py"]="0:0:755"
  ["/usr/local/bin/sharknoc"]="0:0:755"
  ["/usr/local/bin/wallpaper-rotate"]="0:0:755"
  ["/usr/local/lib/jett/jeTT"]="0:0:755"
  ["/usr/local/libexec/nyxus-account-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-backup-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-doctor-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-loginconfig-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-parental-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-pkg-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-security-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-sound-system-default"]="0:0:755"
  ["/usr/local/libexec/nyxus-usbwatch-helper"]="0:0:755"
  ["/usr/local/libexec/nyxus-welcome-helper"]="0:0:755"
  ["/usr/local/sbin/nyxus-firstboot"]="0:0:755"
)
