// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nyxus-mascots/ConstellationN.tsx": () => import("../components/mockups/nyxus-mascots/ConstellationN.tsx"),
  "./components/mockups/nyxus-mascots/Eclipse.tsx": () => import("../components/mockups/nyxus-mascots/Eclipse.tsx"),
  "./components/mockups/nyxus-mascots/EyeOfNyx.tsx": () => import("../components/mockups/nyxus-mascots/EyeOfNyx.tsx"),
  "./components/mockups/waybar/WorkspaceButtons.tsx": () => import("../components/mockups/waybar/WorkspaceButtons.tsx")
};
