export interface MitreTechniqueData {
  id: string;
  name: string;
  description: string;
  tactics: string[];
  platforms: string[];
  detection: string;
  mitigation: string;
  dataSources: string[];
  references: { title: string; url: string }[];
}

export const MITRE_TACTICS = [
  { id: "TA0043", name: "Reconnaissance", description: "Gathering information for future operations." },
  { id: "TA0042", name: "Resource Development", description: "Establishing resources to support operations." },
  { id: "TA0001", name: "Initial Access", description: "Getting into the network." },
  { id: "TA0002", name: "Execution", description: "Running malicious code." },
  { id: "TA0003", name: "Persistence", description: "Maintaining a foothold." },
  { id: "TA0004", name: "Privilege Escalation", description: "Gaining higher-level permissions." },
  { id: "TA0005", name: "Defense Evasion", description: "Avoiding detection." },
  { id: "TA0006", name: "Credential Access", description: "Stealing account credentials." },
  { id: "TA0007", name: "Discovery", description: "Learning about the environment." },
  { id: "TA0008", name: "Lateral Movement", description: "Moving through the environment." },
  { id: "TA0009", name: "Collection", description: "Gathering data of interest." },
  { id: "TA0011", name: "Command and Control", description: "Communicating with compromised systems." },
  { id: "TA0010", name: "Exfiltration", description: "Stealing data." },
  { id: "TA0040", name: "Impact", description: "Manipulating, interrupting, or destroying." },
];

export const MITRE_TECHNIQUES: MitreTechniqueData[] = [
  { id: "T1046", name: "Network Service Scanning", description: "Adversaries may attempt to get a listing of services running on remote hosts.", tactics: ["TA0007"], platforms: ["Linux", "Windows", "macOS"], detection: "Monitor for processes performing many sequential network connection attempts.", mitigation: "Network segmentation, IDS/IPS at perimeter and internal segments.", dataSources: ["Network Traffic", "Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1046/" }] },
  { id: "T1059.001", name: "Command and Scripting Interpreter: PowerShell", description: "Adversaries may abuse PowerShell commands and scripts for execution.", tactics: ["TA0002"], platforms: ["Windows"], detection: "Enable Script Block Logging (Event 4104), AMSI, monitor for -enc and obfuscation.", mitigation: "Constrained Language Mode, AppLocker, signed scripts only.", dataSources: ["Process Creation", "Script Block Logging"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1059/001/" }] },
  { id: "T1059.003", name: "Command and Scripting Interpreter: Windows Command Shell", description: "Adversaries may abuse cmd.exe to execute commands.", tactics: ["TA0002"], platforms: ["Windows"], detection: "Sysmon Event 1 for cmd.exe with suspicious parents/args.", mitigation: "Audit command-line, EDR behavioral detection.", dataSources: ["Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1059/003/" }] },
  { id: "T1059.004", name: "Command and Scripting Interpreter: Unix Shell", description: "Adversaries may use Unix shell commands and scripts.", tactics: ["TA0002"], platforms: ["Linux", "macOS"], detection: "auditd execve logging, look for sh/bash piped from curl/wget.", mitigation: "Restrict shell access, behavioral monitoring.", dataSources: ["Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1059/004/" }] },
  { id: "T1003.001", name: "OS Credential Dumping: LSASS Memory", description: "Adversaries may attempt to access credentials stored in LSASS process memory.", tactics: ["TA0006"], platforms: ["Windows"], detection: "Sysmon Event 10 (ProcessAccess) on lsass.exe with GrantedAccess flags 0x1010, 0x1410, 0x1438.", mitigation: "Enable Credential Guard, RunAsPPL on LSASS, EDR.", dataSources: ["Process Access"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1003/001/" }] },
  { id: "T1053.005", name: "Scheduled Task/Job: Scheduled Task", description: "Adversaries may abuse Windows Task Scheduler to perform task scheduling.", tactics: ["TA0002", "TA0003", "TA0004"], platforms: ["Windows"], detection: "Event 4698 (Task Created), Sysmon Event 1 for schtasks.exe.", mitigation: "Restrict permissions, monitor \\Windows\\System32\\Tasks\\.", dataSources: ["Process Creation", "Scheduled Job"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1053/005/" }] },
  { id: "T1053.003", name: "Scheduled Task/Job: Cron", description: "Adversaries may abuse the cron utility to schedule recurring tasks.", tactics: ["TA0002", "TA0003"], platforms: ["Linux", "macOS"], detection: "auditd watch on /etc/cron.*, /var/spool/cron/.", mitigation: "Baseline cron contents; alert on changes.", dataSources: ["File", "Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1053/003/" }] },
  { id: "T1218.005", name: "System Binary Proxy Execution: Mshta", description: "Adversaries may abuse mshta.exe to execute proxied HTAs.", tactics: ["TA0005"], platforms: ["Windows"], detection: "Sysmon Event 1 for mshta.exe with URL args or unusual parents.", mitigation: "WDAC rule blocking mshta.exe.", dataSources: ["Process Creation"], references: [{ title: "LOLBAS", url: "https://lolbas-project.github.io/lolbas/Binaries/Mshta/" }] },
  { id: "T1218.011", name: "System Binary Proxy Execution: Rundll32", description: "Adversaries may abuse rundll32.exe to proxy execution of malicious code.", tactics: ["TA0005"], platforms: ["Windows"], detection: "Hunt for rundll32 with unusual DLLs or no DLL arg.", mitigation: "AppLocker, WDAC.", dataSources: ["Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1218/011/" }] },
  { id: "T1021.002", name: "Remote Services: SMB/Windows Admin Shares", description: "Adversaries may use Valid Accounts to interact with a remote network share using SMB.", tactics: ["TA0008"], platforms: ["Windows"], detection: "Event 4624 type 3 from non-admin sources; PSEXESVC service install.", mitigation: "Disable SMBv1, LAPS, restrict admin shares.", dataSources: ["Authentication Logs", "Service"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1021/002/" }] },
  { id: "T1021.001", name: "Remote Services: Remote Desktop Protocol", description: "Adversaries may use Valid Accounts to log into a computer using RDP.", tactics: ["TA0008"], platforms: ["Windows"], detection: "Event 4624 type 10, geo-anomalous source IPs.", mitigation: "MFA on RDP, restrict by source, NLA required.", dataSources: ["Logon Sessions"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1021/001/" }] },
  { id: "T1190", name: "Exploit Public-Facing Application", description: "Adversaries may attempt to exploit a weakness in an Internet-facing service.", tactics: ["TA0001"], platforms: ["Linux", "Windows", "macOS"], detection: "WAF alerts, anomalous HTTP responses, IDS signatures.", mitigation: "Patch promptly, WAF, network segmentation, least-privilege app users.", dataSources: ["Application Logs", "Network Traffic"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1190/" }] },
  { id: "T1566.001", name: "Phishing: Spearphishing Attachment", description: "Adversaries may send spearphishing emails with malicious attachments.", tactics: ["TA0001"], platforms: ["Linux", "Windows", "macOS"], detection: "Email gateway sandboxing, Office ASR rule violations.", mitigation: "Disable macros from internet, attachment filtering, user training.", dataSources: ["Email", "File"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1566/001/" }] },
  { id: "T1204.002", name: "User Execution: Malicious File", description: "An adversary may rely upon specific actions by a user in order to gain execution.", tactics: ["TA0002"], platforms: ["Linux", "Windows", "macOS"], detection: "Sysmon parent-child anomalies (winword -> powershell).", mitigation: "Disable macros, ASR rules.", dataSources: ["Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1204/002/" }] },
  { id: "T1027", name: "Obfuscated Files or Information", description: "Adversaries may attempt to make an executable or file difficult to discover or analyze.", tactics: ["TA0005"], platforms: ["Linux", "Windows", "macOS"], detection: "High-entropy strings, base64 in command lines, packed binaries.", mitigation: "EDR behavioral analysis.", dataSources: ["Process Creation", "File"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1027/" }] },
  { id: "T1547.001", name: "Boot or Logon Autostart: Registry Run Keys", description: "Adversaries may achieve persistence by adding a program to a startup folder or registry Run key.", tactics: ["TA0003", "TA0004"], platforms: ["Windows"], detection: "Sysmon Event 13 on CurrentVersion\\Run; Autoruns baseline diff.", mitigation: "Baseline + alert on Run key changes.", dataSources: ["Windows Registry"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1547/001/" }] },
  { id: "T1548.003", name: "Abuse Elevation Control Mechanism: Sudo", description: "Adversaries may perform sudo caching and/or use the sudoers file to elevate privileges.", tactics: ["TA0004", "TA0005"], platforms: ["Linux", "macOS"], detection: "auditd on execve with euid=0 ruid!=0; sudo log review.", mitigation: "Audit sudoers; avoid NOPASSWD; review GTFOBins for allowed binaries.", dataSources: ["Process Creation", "Authentication Logs"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1548/003/" }] },
  { id: "T1558.003", name: "Steal or Forge Kerberos Tickets: Kerberoasting", description: "Adversaries may abuse a valid Kerberos ticket-granting ticket (TGT) to request service tickets for SPNs.", tactics: ["TA0006"], platforms: ["Windows"], detection: "Event 4769 with EncryptionType 0x17, threshold by user per minute.", mitigation: "AES-only tickets, long service account passwords (25+), gMSA.", dataSources: ["Authentication Logs"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1558/003/" }] },
  { id: "T1070.001", name: "Indicator Removal: Clear Windows Event Logs", description: "Adversaries may clear Windows Event Logs to hide activity.", tactics: ["TA0005"], platforms: ["Windows"], detection: "Event 1102 (audit cleared); ship logs to SIEM in real time.", mitigation: "Restrict Manage Auditing user right; centralize logs.", dataSources: ["Windows Event Logs"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1070/001/" }] },
  { id: "T1071.001", name: "Application Layer Protocol: Web Protocols", description: "Adversaries may communicate using HTTP/S to blend in with web traffic.", tactics: ["TA0011"], platforms: ["Linux", "Windows", "macOS"], detection: "Beacon analytics, JA3 fingerprinting, anomalous TLS SNI.", mitigation: "Egress allow-list, TLS inspection.", dataSources: ["Network Traffic"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1071/001/" }] },
  { id: "T1071.004", name: "Application Layer Protocol: DNS", description: "Adversaries may use DNS for C2 or exfiltration.", tactics: ["TA0011"], platforms: ["Linux", "Windows", "macOS"], detection: "Subdomain entropy, query volume per domain.", mitigation: "Internal DNS resolver only, log + analyze.", dataSources: ["DNS"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1071/004/" }] },
  { id: "T1048.003", name: "Exfiltration Over Alternative Protocol", description: "Adversaries may steal data by exfiltrating it over an un-encrypted, non-C2 protocol.", tactics: ["TA0010"], platforms: ["Linux", "Windows", "macOS"], detection: "Anomalous outbound DNS/ICMP/FTP volume.", mitigation: "Egress filtering and DLP.", dataSources: ["Network Traffic"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1048/003/" }] },
  { id: "T1087.002", name: "Account Discovery: Domain Account", description: "Adversaries may enumerate domain accounts via LDAP queries.", tactics: ["TA0007"], platforms: ["Windows"], detection: "LDAP volume per user, BloodHound/SharpHound detection.", mitigation: "MS Defender for Identity, tiered admin.", dataSources: ["Authentication Logs", "Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1087/002/" }] },
  { id: "T1482", name: "Domain Trust Discovery", description: "Adversaries may attempt to gather information on domain trust relationships.", tactics: ["TA0007"], platforms: ["Windows"], detection: "nltest /domain_trusts, dsquery executions.", mitigation: "Restrict cross-trust queries.", dataSources: ["Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1482/" }] },
  { id: "T1490", name: "Inhibit System Recovery", description: "Adversaries may delete backups, shadow copies, or recovery features.", tactics: ["TA0040"], platforms: ["Windows", "Linux", "macOS"], detection: "vssadmin/wmic/wbadmin delete in command lines.", mitigation: "Offline immutable backups, Controlled Folder Access.", dataSources: ["Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1490/" }] },
  { id: "T1486", name: "Data Encrypted for Impact", description: "Adversaries may encrypt data on target systems to interrupt availability.", tactics: ["TA0040"], platforms: ["Linux", "Windows", "macOS"], detection: "High file-modify rate per process, ransom note files.", mitigation: "Backups, EDR ransomware behavioral protection.", dataSources: ["File"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1486/" }] },
  { id: "T1110.003", name: "Brute Force: Password Spraying", description: "Adversaries may use a single password against many accounts.", tactics: ["TA0006"], platforms: ["Linux", "Windows", "macOS", "Cloud"], detection: "Multiple 4625 across many usernames from one source.", mitigation: "MFA, account lockout, conditional access.", dataSources: ["Authentication Logs"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1110/003/" }] },
  { id: "T1110.001", name: "Brute Force: Password Guessing", description: "Adversaries may try many passwords against one account.", tactics: ["TA0006"], platforms: ["any"], detection: "Many 4625 against one user.", mitigation: "Lockout, MFA.", dataSources: ["Authentication Logs"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1110/001/" }] },
  { id: "T1136.001", name: "Create Account: Local Account", description: "Adversaries may create a local account.", tactics: ["TA0003"], platforms: ["Linux", "Windows", "macOS"], detection: "Event 4720 (account created), useradd auditd.", mitigation: "Restrict account creation rights.", dataSources: ["User Account"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1136/001/" }] },
  { id: "T1505.003", name: "Server Software Component: Web Shell", description: "Adversaries may backdoor web servers with web shells.", tactics: ["TA0003"], platforms: ["Linux", "Windows"], detection: "File integrity on webroot, anomalous .php/.aspx files.", mitigation: "Webroot baselining, WAF, least-priv web user.", dataSources: ["File", "Network Traffic"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1505/003/" }] },
  { id: "T1573.002", name: "Encrypted Channel: Asymmetric Cryptography", description: "Adversaries may use asymmetric crypto to protect C2 traffic.", tactics: ["TA0011"], platforms: ["Linux", "Windows", "macOS"], detection: "TLS JA3 fingerprinting, certificate anomalies.", mitigation: "TLS inspection, threat intel.", dataSources: ["Network Traffic"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1573/002/" }] },
  { id: "T1569.002", name: "System Services: Service Execution", description: "Adversaries may abuse the Windows service control manager to execute malicious commands.", tactics: ["TA0002"], platforms: ["Windows"], detection: "Event 7045 (service install) with suspicious binary paths.", mitigation: "Restrict service install rights, baselining.", dataSources: ["Service Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1569/002/" }] },
  { id: "T1140", name: "Deobfuscate/Decode Files or Information", description: "Adversaries may decode/deobfuscate files at runtime.", tactics: ["TA0005"], platforms: ["any"], detection: "Process executing base64 -d, certutil -decode.", mitigation: "EDR script monitoring.", dataSources: ["Process Creation"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1140/" }] },
  { id: "T1105", name: "Ingress Tool Transfer", description: "Adversaries may transfer tools or other files from an external system into a compromised environment.", tactics: ["TA0011"], platforms: ["any"], detection: "Outbound curl/wget/certutil, anomalous binary downloads.", mitigation: "Egress filtering, AV scanning of downloads.", dataSources: ["Network Traffic", "File"], references: [{ title: "MITRE", url: "https://attack.mitre.org/techniques/T1105/" }] },
];

export function getTechnique(id: string): MitreTechniqueData | undefined {
  return MITRE_TECHNIQUES.find((t) => t.id === id);
}
