[General]
background=background.png
blur=false
recursiveBlur=false
blurRadius=0

PasswordFieldCharacter=█
PasswordFieldPlaceholderText=PASSPHRASE

LoginButtonText=AUTHENTICATE

ScreenPadding=0
FontPointSize=13
