# ============================================
# NYXUS — nyx-2026.05.02-x86_64.iso
# Copyright © 2026 Joseph Sierengowski
# All Rights Reserved
# NYX-J5W-2026-SIERENGOWSKI-LOCKED
# ============================================
default 01-nyx.conf
timeout 3
console-mode keep
editor no
