[window]
opacity            = 0.88
padding.x          = 16
padding.y          = 12
decorations        = "None"
startup_mode       = "Windowed"
dynamic_title      = true
dynamic_padding    = false

[window.class]
instance = "Alacritty"
general  = "Alacritty"

[scrolling]
history    = 10000
multiplier = 5

[font]
size = 11.5

[font.normal]
family = "JetBrains Mono Nerd Font"
style  = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style  = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style  = "Italic"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style  = "Bold Italic"

[font.offset]
x = 0
y = 2

[cursor]
style.shape      = "Block"
style.blinking   = "Always"
blink_interval   = 500
unfocused_hollow = true
thickness        = 0.15

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[mouse]
hide_when_typing = true

[bell]
animation = "EaseOutExpo"
duration  = 0
color     = "#f4ead5"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background     = "#0a0a14"
foreground     = "#f4ead5"
dim_foreground = "#f4ead58c"

[colors.cursor]
text   = "#050308"
cursor = "#f4ead5"

[colors.vi_mode_cursor]
text   = "#050308"
cursor = "#f4ead5"

[colors.selection]
text       = "#050308"
background = "#f4ead5"

[colors.search.matches]
foreground = "#050308"
background = "#f4ead5"

[colors.search.focused_match]
foreground = "#050308"
background = "#f4ead5"

[colors.footer_bar]
background = "#050308"
foreground = "#f4ead58c"

[colors.hints.start]
foreground = "#050308"
background = "#f4ead5"

[colors.hints.end]
foreground = "#050308"
background = "#f4ead5"

[colors.normal]
black   = "#050308"
red     = "#f87171"
green   = "#f4ead5"
yellow  = "#f4ead5"
blue    = "#1a1a28"
magenta = "#f4ead5"
cyan    = "#f4ead5"
white   = "#f4ead5"

[colors.bright]
black   = "#0a0a14"
red     = "#f87171"
green   = "#f4ead5"
yellow  = "#f4ead5"
blue    = "#1a1a28"
magenta = "#f4ead5"
cyan    = "#f4ead5"
white   = "#f4ead5"

[colors.dim]
black   = "#000000"
red     = "#f87171"
green   = "#f4ead58c"
yellow  = "#f4ead58c"
blue    = "#1a1a28"
magenta = "#f4ead58c"
cyan    = "#f4ead58c"
white   = "#f4ead58c"

[[keyboard.bindings]]
key    = "V"
mods   = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key    = "C"
mods   = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key    = "Plus"
mods   = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key    = "Minus"
mods   = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key    = "Key0"
mods   = "Control"
action = "ResetFontSize"
