kind = "web"
previewPath = "/"
title = "NYXUS Download Portal"
version = "1.0.0"
id = "artifacts/nyxus-web"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18304

[services.development]
run = "pnpm --filter @workspace/nyxus-web run dev"

[services.env]
PORT = "18304"
BASE_PATH = "/"
