# NYXUS · lock-screen cava — wider spectrum for the frosted glass lock.
[general]
framerate = 30
bars = 40
autosens = 1
sleep_timer = 3

[input]
method = pulse

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7

[smoothing]
noise_reduction = 60
monstercat = 1
