#!/usr/bin/env python3
# ============================================================================
#  nyxus_settings_accessibility.py · NYXUS · Accessibility   rev 2026-05-13 r1
#
#  Standalone GTK4 panel for Settings → Accessibility (P6.32).
#
#  Toggles user-scope state only — never edits root files. Profile choice
#  rewrites ~/.local/share/orca/user-settings.conf (which the orca preset
#  shipped under /etc/skel seeds at first login). High-contrast variant
#  flips the GTK theme via the gsettings interface schema. Magnifier
#  toggle just exec's `gsettings set org.gnome.desktop.a11y.applications`.
#
#  © 2026 JOSEPH SIERENGOWSKI · NYX-J5W-2026-SIERENGOWSKI-LOCKED
# ============================================================================
from __future__ import annotations

import json
import logging
import shutil
import subprocess
from pathlib import Path

import gi  # type: ignore[import-not-found]

gi.require_version("Gtk", "4.0")
gi.require_version("Adw", "1")
from gi.repository import Adw, GLib, Gtk  # noqa: E402

LOG_DIR = Path.home() / ".cache" / "nyxus"
LOG_DIR.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    filename=str(LOG_DIR / "accessibility.log"),
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
log = logging.getLogger("nyxus_a11y")

ORCA_CONF = Path.home() / ".local" / "share" / "orca" / "user-settings.conf"

PROFILES = ("default", "low-vision", "screen-reader")


def _gsettings(*args: str) -> tuple[bool, str]:
    if not shutil.which("gsettings"):
        return False, "gsettings missing"
    try:
        proc = subprocess.run(
            ["gsettings", *args],
            capture_output=True, text=True, check=False, timeout=10,
        )
    except subprocess.TimeoutExpired:
        return False, "gsettings timed out"
    if proc.returncode != 0:
        return False, proc.stderr.strip() or f"rc={proc.returncode}"
    return True, proc.stdout.rstrip()


def _read_orca() -> dict:
    if not ORCA_CONF.exists():
        return {"general": {}, "activeProfile": "default"}
    try:
        return json.loads(ORCA_CONF.read_text())
    except Exception as exc:  # pragma: no cover
        log.warning("orca read: %s", exc)
        return {"general": {}, "activeProfile": "default"}


def _write_orca(doc: dict) -> None:
    ORCA_CONF.parent.mkdir(parents=True, exist_ok=True)
    tmp = ORCA_CONF.with_suffix(".tmp")
    tmp.write_text(json.dumps(doc, indent=2))
    tmp.replace(ORCA_CONF)


# ──────────────────────────────────────────────────────────────────────
# Hyprland a11y snippet — persisted toggle store
#
# Sticky keys / visual bell are stored in a single JSON sidecar so we
# can round-trip the UI state, plus a small Hyprland conf snippet that
# is sourced from ~/.config/hypr/conf.d/. The snippet is regenerated
# from the JSON every time a toggle flips, so the two never drift.
# Hyprland auto-sources conf.d/* so no `source =` line is needed in
# hyprland.conf for it to take effect on next reload.
# ──────────────────────────────────────────────────────────────────────
HYPR_CONFD       = Path.home() / ".config" / "hypr" / "conf.d"
A11Y_SNIPPET     = HYPR_CONFD / "nyxus-a11y.conf"
A11Y_STATE_JSON  = Path.home() / ".config" / "nyxus" / "a11y.json"


def _a11y_state_read() -> dict:
    if not A11Y_STATE_JSON.exists():
        return {}
    try:
        return json.loads(A11Y_STATE_JSON.read_text()) or {}
    except Exception as exc:
        log.warning("a11y state read: %s", exc)
        return {}


def _a11y_state_write(state: dict) -> None:
    A11Y_STATE_JSON.parent.mkdir(parents=True, exist_ok=True)
    tmp = A11Y_STATE_JSON.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=2))
    tmp.replace(A11Y_STATE_JSON)


def _a11y_snippet_get(key: str, default: bool) -> bool:
    return bool(_a11y_state_read().get(key, default))


def _a11y_snippet_set(key: str, value: bool) -> None:
    state = _a11y_state_read()
    state[key] = bool(value)
    _a11y_state_write(state)
    _a11y_snippet_render(state)


def _a11y_snippet_render(state: dict) -> None:
    """Regenerate the Hyprland conf snippet from the JSON state."""
    HYPR_CONFD.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by NYXUS Settings · Accessibility — do not edit.",
        "# Source of truth: ~/.config/nyxus/a11y.json",
        "",
    ]
    if state.get("sticky_keys"):
        lines.append("input { kb_options = ctrl:nocaps,sticky_keys }")
    if state.get("visual_bell"):
        # Hyprland has no first-class visual-bell; we proxy it through
        # the active-window border colour (cream → copper gradient) so
        # the focused window flashes when the system bell rings.
        # rgba() takes exactly 8 hex digits (rrggbbaa).
        lines.append("general { col.active_border = "
                     "rgba(f4ead5dd) rgba(b8865aff) 45deg }")
    tmp = A11Y_SNIPPET.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n")
    tmp.replace(A11Y_SNIPPET)


def _hyprctl_keyword(key: str, value: str) -> tuple[bool, str]:
    """Apply a Hyprland keyword live (no reload) — best-effort."""
    if not shutil.which("hyprctl"):
        return False, "hyprctl missing"
    try:
        proc = subprocess.run(
            ["hyprctl", "keyword", key, value],
            capture_output=True, text=True, check=False, timeout=5,
        )
    except subprocess.TimeoutExpired:
        return False, "hyprctl timed out"
    if proc.returncode != 0:
        return False, proc.stderr.strip() or f"rc={proc.returncode}"
    return True, proc.stdout.rstrip()


# ── GTK panel ───────────────────────────────────────────────────────────
class A11yPanel(Gtk.Box):
    def __init__(self) -> None:
        super().__init__(orientation=Gtk.Orientation.VERTICAL, spacing=12)
        self.set_margin_top(16)
        self.set_margin_bottom(16)
        self.set_margin_start(16)
        self.set_margin_end(16)

        page = Adw.PreferencesPage()
        scroller = Gtk.ScrolledWindow(hexpand=True, vexpand=True)
        scroller.set_child(page)
        self.append(scroller)

        # ── Vision ───────────────────────────────────────────────────
        vision = Adw.PreferencesGroup(
            title="Vision",
            description=(
                "Theme + magnifier toggles for users with low vision. "
                "All changes apply to your account only."
            ),
        )

        # High-contrast variant — uses the GNOME a11y interface schema, which
        # is the canonical key for forcing the high-contrast theme. Setting
        # color-scheme=prefer-dark would only flip dark/light, not contrast.
        ok, current = _gsettings("get",
                                  "org.gnome.desktop.a11y.interface",
                                  "high-contrast")
        is_high_contrast = "true" in (current or "").lower()
        self.contrast = Adw.SwitchRow(
            title="High-contrast theme",
            subtitle="Forces the high-contrast theme variant.",
            active=is_high_contrast,
        )
        self.contrast.connect("notify::active", self._on_contrast_toggled)
        vision.add(self.contrast)

        # Magnifier.
        ok, mag = _gsettings("get",
                              "org.gnome.desktop.a11y.applications",
                              "screen-magnifier-enabled")
        self.mag = Adw.SwitchRow(
            title="Screen magnifier",
            subtitle="Toggle with Super + Plus once enabled.",
            active="true" in (mag or "").lower(),
        )
        self.mag.connect("notify::active", self._on_mag_toggled)
        vision.add(self.mag)
        page.add(vision)

        # ── Hearing / motor (real wired toggles) ────────────────────
        #
        # Sticky keys and visual bell are persisted as Hyprland keyword
        # overrides in ~/.config/hypr/conf.d/nyxus-a11y.conf. Hyprland
        # auto-sources every file in conf.d/, so the snippet survives
        # reloads. Each toggle:
        #   1. rewrites the snippet to the new value,
        #   2. calls `hyprctl keyword` to apply live without a reload,
        #   3. mirrors the value into the org.gnome.desktop.a11y schema
        #      so GTK apps (Files, Settings itself) see the same state.
        hm = Adw.PreferencesGroup(
            title="Hearing & motor",
            description="Sticky keys and visual bell. Saved to "
                        "~/.config/hypr/conf.d/nyxus-a11y.conf and "
                        "applied live via hyprctl.",
        )
        self.sticky = Adw.SwitchRow(
            title="Sticky keys",
            subtitle="Hold modifiers (Shift, Ctrl, Super) one key at a time.",
            active=_a11y_snippet_get("sticky_keys", False),
        )
        self.sticky.connect("notify::active", self._on_sticky_toggled)
        hm.add(self.sticky)
        self.vbell = Adw.SwitchRow(
            title="Visual bell",
            subtitle="Flash the focused window on terminal/system bell.",
            active=_a11y_snippet_get("visual_bell", False),
        )
        self.vbell.connect("notify::active", self._on_vbell_toggled)
        hm.add(self.vbell)
        page.add(hm)

        # ── Orca screen reader ──────────────────────────────────────
        orca = Adw.PreferencesGroup(
            title="Screen reader (Orca)",
            description=(
                "Choose an Orca profile. The `default` profile keeps "
                "speech off; `low-vision` enables magnifier + speech; "
                "`screen-reader` enables full speech, key-echo, braille."
            ),
        )
        doc = _read_orca()
        active = str(doc.get("activeProfile", "default"))
        self.profile_combo = Adw.ComboRow(title="Active profile")
        model = Gtk.StringList.new(PROFILES)
        self.profile_combo.set_model(model)
        try:
            self.profile_combo.set_selected(PROFILES.index(active))
        except ValueError:
            self.profile_combo.set_selected(0)
        self.profile_combo.connect("notify::selected", self._on_profile_change)
        orca.add(self.profile_combo)
        page.add(orca)

        # status banner
        self.banner = Gtk.Label(label="", xalign=0)
        self.banner.add_css_class("dim-label")
        self.append(self.banner)

    # ── handlers ────────────────────────────────────────────────────
    def _on_contrast_toggled(self, sw: Adw.SwitchRow, *_: object) -> None:
        ok, msg = _gsettings(
            "set", "org.gnome.desktop.a11y.interface", "high-contrast",
            "true" if sw.get_active() else "false",
        )
        self._flash(
            "Updated high-contrast theme." if ok else f"Failed: {msg}", ok,
        )

    def _on_mag_toggled(self, sw: Adw.SwitchRow, *_: object) -> None:
        ok, msg = _gsettings(
            "set", "org.gnome.desktop.a11y.applications",
            "screen-magnifier-enabled",
            "true" if sw.get_active() else "false",
        )
        self._flash("Magnifier updated." if ok else f"Failed: {msg}", ok)

    def _on_sticky_toggled(self, sw: Adw.SwitchRow, *_: object) -> None:
        on = sw.get_active()
        try:
            _a11y_snippet_set("sticky_keys", on)
            ok, msg = _hyprctl_keyword("input:kb_options",
                                       "ctrl:nocaps,sticky_keys" if on else "ctrl:nocaps")
            _gsettings("set", "org.gnome.desktop.a11y.keyboard",
                       "stickykeys-enable", "true" if on else "false")
            self._flash("Sticky keys " + ("enabled." if on else "disabled."), ok)
        except Exception as exc:
            self._flash(f"Sticky keys failed: {exc}", False)

    def _on_vbell_toggled(self, sw: Adw.SwitchRow, *_: object) -> None:
        on = sw.get_active()
        try:
            _a11y_snippet_set("visual_bell", on)
            # Apply the same border-colour change live so the user sees
            # the visual-bell colour switch immediately. This matches
            # exactly what the persisted snippet writes on next reload.
            if on:
                ok, _msg = _hyprctl_keyword(
                    "general:col.active_border",
                    "rgba(f4ead5dd) rgba(b8865aff) 45deg")
            else:
                ok, _msg = _hyprctl_keyword(
                    "general:col.active_border",
                    "rgba(b8865aff) rgba(b8865aff) 0deg")
            _gsettings("set", "org.gnome.desktop.wm.preferences",
                       "visual-bell", "true" if on else "false")
            self._flash("Visual bell " + ("enabled." if on else "disabled."), ok)
        except Exception as exc:
            self._flash(f"Visual bell failed: {exc}", False)

    def _on_profile_change(self, combo: Adw.ComboRow, *_: object) -> None:
        idx = combo.get_selected()
        if idx < 0 or idx >= len(PROFILES):
            return
        doc = _read_orca()
        doc["activeProfile"] = PROFILES[idx]
        try:
            _write_orca(doc)
            self._flash(f"Orca profile → {PROFILES[idx]}.", True)
        except Exception as exc:  # pragma: no cover
            self._flash(f"Could not write orca config: {exc}", False)

    def _flash(self, msg: str, success: bool) -> None:
        self.banner.set_label(msg)
        css = "success" if success else "error"
        self.banner.add_css_class(css)
        def _clear() -> bool:
            self.banner.remove_css_class(css)
            return False
        GLib.timeout_add_seconds(3, _clear)


def main() -> int:
    app = Adw.Application(application_id="com.nyxus.accessibility")
    def on_activate(_a: Adw.Application) -> None:
        win = Adw.ApplicationWindow(application=_a,
                                    title="NYXUS · Accessibility")
        win.set_default_size(720, 600)
        win.set_content(A11yPanel())
        win.present()
    app.connect("activate", on_activate)
    return app.run(None)


if __name__ == "__main__":
    raise SystemExit(main())
